// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors

pub mod browser_engine_tests;
pub mod context_tests;
pub mod form_tests;
pub mod lifecycle_tests;
pub mod lp_tests;
pub mod node_tests;
pub mod privacy_tests;
pub mod registry_tests;
pub mod staking_tests;
pub mod tabs_tests;
pub mod types_tests;

use crate::test::framework::{TestCase, TestSuite};

pub fn run_all() -> bool {
    let mut suite = TestSuite::new("Apps");

    suite.add(TestCase::new(
        "app_id_new_increments",
        types_tests::test_app_id_new_increments,
        "apps/types",
    ));
    suite.add(TestCase::new(
        "app_id_system_is_zero",
        types_tests::test_app_id_system_is_zero,
        "apps/types",
    ));
    suite.add(TestCase::new("app_id_from_raw", types_tests::test_app_id_from_raw, "apps/types"));
    suite.add(TestCase::new("app_id_display", types_tests::test_app_id_display, "apps/types"));
    suite.add(TestCase::new("app_id_default", types_tests::test_app_id_default, "apps/types"));
    suite.add(TestCase::new("app_id_equality", types_tests::test_app_id_equality, "apps/types"));
    suite.add(TestCase::new("app_id_ordering", types_tests::test_app_id_ordering, "apps/types"));
    suite.add(TestCase::new("app_id_hash", types_tests::test_app_id_hash, "apps/types"));
    suite.add(TestCase::new("app_type_as_str", types_tests::test_app_type_as_str, "apps/types"));
    suite.add(TestCase::new("app_type_icon", types_tests::test_app_type_icon, "apps/types"));
    suite.add(TestCase::new(
        "app_type_requires_network",
        types_tests::test_app_type_requires_network,
        "apps/types",
    ));
    suite.add(TestCase::new(
        "app_type_requires_crypto",
        types_tests::test_app_type_requires_crypto,
        "apps/types",
    ));
    suite.add(TestCase::new("app_type_default", types_tests::test_app_type_default, "apps/types"));
    suite.add(TestCase::new(
        "app_type_equality",
        types_tests::test_app_type_equality,
        "apps/types",
    ));
    suite.add(TestCase::new("app_type_clone", types_tests::test_app_type_clone, "apps/types"));
    suite.add(TestCase::new("app_error_as_str", types_tests::test_app_error_as_str, "apps/types"));
    suite.add(TestCase::new(
        "app_error_display",
        types_tests::test_app_error_display,
        "apps/types",
    ));
    suite.add(TestCase::new(
        "app_error_equality",
        types_tests::test_app_error_equality,
        "apps/types",
    ));
    suite.add(TestCase::new("app_error_clone", types_tests::test_app_error_clone, "apps/types"));
    suite.add(TestCase::new("app_result_ok", types_tests::test_app_result_ok, "apps/types"));
    suite.add(TestCase::new("app_result_err", types_tests::test_app_result_err, "apps/types"));
    suite.add(TestCase::new("app_type_repr", types_tests::test_app_type_repr, "apps/types"));
    suite.add(TestCase::new(
        "all_app_types_have_icons",
        types_tests::test_all_app_types_have_icons,
        "apps/types",
    ));
    suite.add(TestCase::new(
        "all_app_types_have_str",
        types_tests::test_all_app_types_have_str,
        "apps/types",
    ));

    suite.add(TestCase::new(
        "lifecycle_state_as_str",
        lifecycle_tests::test_lifecycle_state_as_str,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_is_active",
        lifecycle_tests::test_lifecycle_state_is_active,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_can_start",
        lifecycle_tests::test_lifecycle_state_can_start,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_can_stop",
        lifecycle_tests::test_lifecycle_state_can_stop,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_can_suspend",
        lifecycle_tests::test_lifecycle_state_can_suspend,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_can_resume",
        lifecycle_tests::test_lifecycle_state_can_resume,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_default",
        lifecycle_tests::test_lifecycle_state_default,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_display",
        lifecycle_tests::test_lifecycle_state_display,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_equality",
        lifecycle_tests::test_lifecycle_state_equality,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_clone",
        lifecycle_tests::test_lifecycle_state_clone,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_copy",
        lifecycle_tests::test_lifecycle_state_copy,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_repr",
        lifecycle_tests::test_lifecycle_state_repr,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_started_app_id",
        lifecycle_tests::test_app_event_started_app_id,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_stopped_app_id",
        lifecycle_tests::test_app_event_stopped_app_id,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_suspended_app_id",
        lifecycle_tests::test_app_event_suspended_app_id,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_resumed_app_id",
        lifecycle_tests::test_app_event_resumed_app_id,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_failed_app_id",
        lifecycle_tests::test_app_event_failed_app_id,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_permission_granted_app_id",
        lifecycle_tests::test_app_event_permission_granted_app_id,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_permission_revoked_app_id",
        lifecycle_tests::test_app_event_permission_revoked_app_id,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_name_started",
        lifecycle_tests::test_app_event_name_started,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_name_stopped",
        lifecycle_tests::test_app_event_name_stopped,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_name_suspended",
        lifecycle_tests::test_app_event_name_suspended,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_name_resumed",
        lifecycle_tests::test_app_event_name_resumed,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_name_failed",
        lifecycle_tests::test_app_event_name_failed,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_name_permission_granted_is_none",
        lifecycle_tests::test_app_event_name_permission_granted_is_none,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_name_permission_revoked_is_none",
        lifecycle_tests::test_app_event_name_permission_revoked_is_none,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "event_queue_emit_and_poll",
        lifecycle_tests::test_event_queue_emit_and_poll,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "event_queue_peek",
        lifecycle_tests::test_event_queue_peek,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "event_queue_count",
        lifecycle_tests::test_event_queue_count,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "event_queue_clear",
        lifecycle_tests::test_event_queue_clear,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "event_queue_poll_empty",
        lifecycle_tests::test_event_queue_poll_empty,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "event_queue_peek_empty",
        lifecycle_tests::test_event_queue_peek_empty,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "event_fifo_order",
        lifecycle_tests::test_event_fifo_order,
        "apps/lifecycle",
    ));
    suite.add(TestCase::new(
        "app_event_clone",
        lifecycle_tests::test_app_event_clone,
        "apps/lifecycle",
    ));

    suite.add(TestCase::new(
        "permission_level_denied",
        context_tests::test_permission_level_denied,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "permission_level_readonly",
        context_tests::test_permission_level_readonly,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "permission_level_readwrite",
        context_tests::test_permission_level_readwrite,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "permission_level_full",
        context_tests::test_permission_level_full,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "permission_level_default",
        context_tests::test_permission_level_default,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "permission_level_ordering",
        context_tests::test_permission_level_ordering,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "permission_level_repr",
        context_tests::test_permission_level_repr,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_permissions_none",
        context_tests::test_app_permissions_none,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_permissions_individual",
        context_tests::test_app_permissions_individual,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_permissions_browser_preset",
        context_tests::test_app_permissions_browser_preset,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_permissions_wallet_preset",
        context_tests::test_app_permissions_wallet_preset,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_permissions_ecosystem_preset",
        context_tests::test_app_permissions_ecosystem_preset,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_permissions_combine",
        context_tests::test_app_permissions_combine,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_permissions_default",
        context_tests::test_app_permissions_default,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_new",
        context_tests::test_app_context_new,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_with_permissions",
        context_tests::test_app_context_with_permissions,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_id_unique",
        context_tests::test_app_context_id_unique,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_mark_started",
        context_tests::test_app_context_mark_started,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_mark_active",
        context_tests::test_app_context_mark_active,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_memory_tracking",
        context_tests::test_app_context_memory_tracking,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_memory_free_overflow",
        context_tests::test_app_context_memory_free_overflow,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_state",
        context_tests::test_app_context_state,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_state_update",
        context_tests::test_app_context_state_update,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_remove_state",
        context_tests::test_app_context_remove_state,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_clear_state",
        context_tests::test_app_context_clear_state,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_state_keys",
        context_tests::test_app_context_state_keys,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_uptime",
        context_tests::test_app_context_uptime,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_context_idle",
        context_tests::test_app_context_idle,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "permission_level_clone",
        context_tests::test_permission_level_clone,
        "apps/context",
    ));
    suite.add(TestCase::new(
        "app_permissions_clone",
        context_tests::test_app_permissions_clone,
        "apps/context",
    ));

    suite.add(TestCase::new("app_info_new", registry_tests::test_app_info_new, "apps/registry"));
    suite.add(TestCase::new("app_entry_new", registry_tests::test_app_entry_new, "apps/registry"));
    suite.add(TestCase::new(
        "app_entry_info_accessors",
        registry_tests::test_app_entry_info_accessors,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_state",
        registry_tests::test_app_entry_state,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_is_running",
        registry_tests::test_app_entry_is_running,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_create_context",
        registry_tests::test_app_entry_create_context,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_context_properties",
        registry_tests::test_app_entry_context_properties,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_destroy_context",
        registry_tests::test_app_entry_destroy_context,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_context_mut",
        registry_tests::test_app_entry_context_mut,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_registered_at",
        registry_tests::test_app_entry_registered_at,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_uptime_no_context",
        registry_tests::test_app_entry_uptime_no_context,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_uptime_with_context",
        registry_tests::test_app_entry_uptime_with_context,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_info_fields",
        registry_tests::test_app_info_fields,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "multiple_entries",
        registry_tests::test_multiple_entries,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "lifecycle_state_transitions",
        registry_tests::test_lifecycle_state_transitions,
        "apps/registry",
    ));
    suite.add(TestCase::new(
        "app_entry_info_reference",
        registry_tests::test_app_entry_info_reference,
        "apps/registry",
    ));

    suite.add(TestCase::new(
        "url_encode_unreserved",
        form_tests::test_url_encode_unreserved,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "url_encode_space",
        form_tests::test_url_encode_space,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "url_encode_special_chars",
        form_tests::test_url_encode_special_chars,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "url_encode_unicode",
        form_tests::test_url_encode_unicode,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "url_encode_empty",
        form_tests::test_url_encode_empty,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "url_encode_numbers",
        form_tests::test_url_encode_numbers,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "url_encode_mixed",
        form_tests::test_url_encode_mixed,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "build_form_urlencoded_empty",
        form_tests::test_build_form_urlencoded_empty,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "build_form_urlencoded_single",
        form_tests::test_build_form_urlencoded_single,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "build_form_urlencoded_multiple",
        form_tests::test_build_form_urlencoded_multiple,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "build_form_urlencoded_special_name",
        form_tests::test_build_form_urlencoded_special_name,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "build_form_urlencoded_empty_value",
        form_tests::test_build_form_urlencoded_empty_value,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "resolve_url_absolute",
        form_tests::test_resolve_url_absolute,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "resolve_url_empty_action",
        form_tests::test_resolve_url_empty_action,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "resolve_url_absolute_path",
        form_tests::test_resolve_url_absolute_path,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "resolve_url_relative_path",
        form_tests::test_resolve_url_relative_path,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "resolve_url_protocol_relative",
        form_tests::test_resolve_url_protocol_relative,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "resolve_url_http_protocol_relative",
        form_tests::test_resolve_url_http_protocol_relative,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "resolve_url_deep_relative",
        form_tests::test_resolve_url_deep_relative,
        "apps/browser/form",
    ));
    suite.add(TestCase::new(
        "resolve_url_root_relative",
        form_tests::test_resolve_url_root_relative,
        "apps/browser/form",
    ));

    suite.add(TestCase::new(
        "node_type_element",
        browser_engine_tests::test_node_type_element,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "node_type_text",
        browser_engine_tests::test_node_type_text,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "node_type_comment",
        browser_engine_tests::test_node_type_comment,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "node_new_element",
        browser_engine_tests::test_node_new_element,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "node_with_children",
        browser_engine_tests::test_node_with_children,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "node_with_attributes",
        browser_engine_tests::test_node_with_attributes,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "document_new",
        browser_engine_tests::test_document_new,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "document_with_title",
        browser_engine_tests::test_document_with_title,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "document_noscript_redirect",
        browser_engine_tests::test_document_noscript_redirect,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "document_hidden_classes",
        browser_engine_tests::test_document_hidden_classes,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "node_type_clone",
        browser_engine_tests::test_node_type_clone,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "node_clone",
        browser_engine_tests::test_node_clone,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "document_clone",
        browser_engine_tests::test_document_clone,
        "apps/browser/engine",
    ));
    suite.add(TestCase::new(
        "nested_nodes",
        browser_engine_tests::test_nested_nodes,
        "apps/browser/engine",
    ));

    suite.add(TestCase::new(
        "tab_status_loading",
        tabs_tests::test_tab_status_loading,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "tab_status_ready",
        tabs_tests::test_tab_status_ready,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "tab_status_error",
        tabs_tests::test_tab_status_error,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "tab_status_blank",
        tabs_tests::test_tab_status_blank,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "tab_status_equality",
        tabs_tests::test_tab_status_equality,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "tab_status_clone",
        tabs_tests::test_tab_status_clone,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "tab_status_copy",
        tabs_tests::test_tab_status_copy,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "security_status_secure",
        tabs_tests::test_security_status_secure,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "security_status_insecure",
        tabs_tests::test_security_status_insecure,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "security_status_mixed",
        tabs_tests::test_security_status_mixed,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "security_status_unknown",
        tabs_tests::test_security_status_unknown,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "security_status_equality",
        tabs_tests::test_security_status_equality,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "security_status_clone",
        tabs_tests::test_security_status_clone,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "browser_tab_new",
        tabs_tests::test_browser_tab_new,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "browser_tab_url",
        tabs_tests::test_browser_tab_url,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "browser_tab_security",
        tabs_tests::test_browser_tab_security,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "browser_tab_error",
        tabs_tests::test_browser_tab_error,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "browser_tab_history",
        tabs_tests::test_browser_tab_history,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "browser_tab_favicon",
        tabs_tests::test_browser_tab_favicon,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "browser_tab_scroll",
        tabs_tests::test_browser_tab_scroll,
        "apps/browser/tabs",
    ));
    suite.add(TestCase::new(
        "browser_tab_clone",
        tabs_tests::test_browser_tab_clone,
        "apps/browser/tabs",
    ));

    suite.add(TestCase::new("privacy_init", privacy_tests::test_privacy_init, "apps/privacy"));
    suite.add(TestCase::new(
        "privacy_start_stop",
        privacy_tests::test_privacy_start_stop,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "privacy_stats_default",
        privacy_tests::test_privacy_stats_default,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "privacy_stats_total_requests",
        privacy_tests::test_privacy_stats_total_requests,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "privacy_stats_block_rate_zero",
        privacy_tests::test_privacy_stats_block_rate_zero,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "privacy_stats_block_rate_50_percent",
        privacy_tests::test_privacy_stats_block_rate_50_percent,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "privacy_stats_block_rate_100_percent",
        privacy_tests::test_privacy_stats_block_rate_100_percent,
        "apps/privacy",
    ));
    suite.add(TestCase::new("reset_stats", privacy_tests::test_reset_stats, "apps/privacy"));
    suite.add(TestCase::new(
        "increment_params_stripped",
        privacy_tests::test_increment_params_stripped,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "increment_fingerprint_blocked",
        privacy_tests::test_increment_fingerprint_blocked,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "increment_cookies_blocked",
        privacy_tests::test_increment_cookies_blocked,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "is_tracker_exact_match",
        privacy_tests::test_is_tracker_exact_match,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "is_tracker_subdomain",
        privacy_tests::test_is_tracker_subdomain,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "is_tracker_case_insensitive",
        privacy_tests::test_is_tracker_case_insensitive,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "is_tracker_not_tracker",
        privacy_tests::test_is_tracker_not_tracker,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "is_tracker_partial_match_not_blocked",
        privacy_tests::test_is_tracker_partial_match_not_blocked,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "blocked_domains_not_empty",
        privacy_tests::test_blocked_domains_not_empty,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "blocked_domain_count",
        privacy_tests::test_blocked_domain_count,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "should_block_tracker_url",
        privacy_tests::test_should_block_tracker_url,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "should_block_safe_url",
        privacy_tests::test_should_block_safe_url,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "should_block_subdomain_tracker",
        privacy_tests::test_should_block_subdomain_tracker,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_tracking_params_utm",
        privacy_tests::test_strip_tracking_params_utm,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_tracking_params_fbclid",
        privacy_tests::test_strip_tracking_params_fbclid,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_tracking_params_gclid",
        privacy_tests::test_strip_tracking_params_gclid,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_tracking_params_multiple",
        privacy_tests::test_strip_tracking_params_multiple,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_tracking_params_preserves_fragment",
        privacy_tests::test_strip_tracking_params_preserves_fragment,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_tracking_params_no_query",
        privacy_tests::test_strip_tracking_params_no_query,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_tracking_params_empty_after_strip",
        privacy_tests::test_strip_tracking_params_empty_after_strip,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_tracking_params_preserves_legit_params",
        privacy_tests::test_strip_tracking_params_preserves_legit_params,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "clean_url_decodes_amp",
        privacy_tests::test_clean_url_decodes_amp,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "clean_url_removes_trailing_question_mark",
        privacy_tests::test_clean_url_removes_trailing_question_mark,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "tracking_param_count_positive",
        privacy_tests::test_tracking_param_count_positive,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_all_utm_variants",
        privacy_tests::test_strip_all_utm_variants,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_social_trackers",
        privacy_tests::test_strip_social_trackers,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "strip_analytics_params",
        privacy_tests::test_strip_analytics_params,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "blocked_domains_contains_major_trackers",
        privacy_tests::test_blocked_domains_contains_major_trackers,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "url_with_only_tracking_params",
        privacy_tests::test_url_with_only_tracking_params,
        "apps/privacy",
    ));
    suite.add(TestCase::new(
        "mixed_case_tracking_params",
        privacy_tests::test_mixed_case_tracking_params,
        "apps/privacy",
    ));

    suite.add(TestCase::new(
        "network_mainnet_staking_contract",
        staking_tests::test_network_mainnet_staking_contract,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "network_sepolia_staking_contract",
        staking_tests::test_network_sepolia_staking_contract,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "network_mainnet_nox_token",
        staking_tests::test_network_mainnet_nox_token,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "network_sepolia_nox_token",
        staking_tests::test_network_sepolia_nox_token,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "network_mainnet_chain_id",
        staking_tests::test_network_mainnet_chain_id,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "network_sepolia_chain_id",
        staking_tests::test_network_sepolia_chain_id,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "network_equality",
        staking_tests::test_network_equality,
        "apps/staking",
    ));
    suite.add(TestCase::new("network_clone", staking_tests::test_network_clone, "apps/staking"));
    suite.add(TestCase::new("network_copy", staking_tests::test_network_copy, "apps/staking"));
    suite.add(TestCase::new("calculate_apy", staking_tests::test_calculate_apy, "apps/staking"));
    suite.add(TestCase::new(
        "calculate_apy_zero_staked",
        staking_tests::test_calculate_apy_zero_staked,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "calculate_apy_zero_rewards",
        staking_tests::test_calculate_apy_zero_rewards,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "estimate_rewards",
        staking_tests::test_estimate_rewards,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "estimate_rewards_staked_amount",
        staking_tests::test_estimate_rewards_staked_amount,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "estimate_rewards_apy",
        staking_tests::test_estimate_rewards_apy,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "calculate_yearly_rewards",
        staking_tests::test_calculate_yearly_rewards,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "calculate_yearly_rewards_zero_stake",
        staking_tests::test_calculate_yearly_rewards_zero_stake,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "calculate_yearly_rewards_zero_apy",
        staking_tests::test_calculate_yearly_rewards_zero_apy,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "calculate_rewards_for_period",
        staking_tests::test_calculate_rewards_for_period,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "calculate_rewards_for_period_zero_seconds",
        staking_tests::test_calculate_rewards_for_period_zero_seconds,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "compound_rewards_greater_than_simple",
        staking_tests::test_compound_rewards_greater_than_simple,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "compound_rewards_once",
        staking_tests::test_compound_rewards_once,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "calculate_effective_apy_single_compound",
        staking_tests::test_calculate_effective_apy_single_compound,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "calculate_effective_apy_multiple_compounds",
        staking_tests::test_calculate_effective_apy_multiple_compounds,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "format_duration_seconds",
        staking_tests::test_format_duration_seconds,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "format_duration_minutes",
        staking_tests::test_format_duration_minutes,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "format_duration_hours",
        staking_tests::test_format_duration_hours,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "format_duration_days",
        staking_tests::test_format_duration_days,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "format_duration_months",
        staking_tests::test_format_duration_months,
        "apps/staking",
    ));
    suite.add(TestCase::new(
        "rewards_info_apy_percentage",
        staking_tests::test_rewards_info_apy_percentage,
        "apps/staking",
    ));

    suite.add(TestCase::new(
        "node_type_element_creation",
        node_tests::test_node_type_element_creation,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_type_text_creation",
        node_tests::test_node_type_text_creation,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_type_comment_creation",
        node_tests::test_node_type_comment_creation,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_empty_children",
        node_tests::test_node_empty_children,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_with_single_child",
        node_tests::test_node_with_single_child,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_with_multiple_children",
        node_tests::test_node_with_multiple_children,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_single_attribute",
        node_tests::test_node_single_attribute,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_multiple_attributes",
        node_tests::test_node_multiple_attributes,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_class_attribute",
        node_tests::test_node_class_attribute,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_id_attribute",
        node_tests::test_node_id_attribute,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_deeply_nested",
        node_tests::test_node_deeply_nested,
        "apps/browser/node",
    ));
    suite.add(TestCase::new("node_clone", node_tests::test_node_clone, "apps/browser/node"));
    suite.add(TestCase::new(
        "node_type_clone",
        node_tests::test_node_type_clone,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_mixed_children",
        node_tests::test_node_mixed_children,
        "apps/browser/node",
    ));
    suite.add(TestCase::new(
        "node_data_attributes",
        node_tests::test_node_data_attributes,
        "apps/browser/node",
    ));

    suite.add(TestCase::new(
        "rewards_info_daily_rewards",
        lp_tests::test_rewards_info_daily_rewards,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_weekly_rewards",
        lp_tests::test_rewards_info_weekly_rewards,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_monthly_rewards",
        lp_tests::test_rewards_info_monthly_rewards,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_yearly_rewards",
        lp_tests::test_rewards_info_yearly_rewards,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_staked_amount",
        lp_tests::test_rewards_info_staked_amount,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_pending_rewards_initial",
        lp_tests::test_rewards_info_pending_rewards_initial,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_apy_basis_points",
        lp_tests::test_rewards_info_apy_basis_points,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_apy_percentage",
        lp_tests::test_rewards_info_apy_percentage,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_apy_percentage_5",
        lp_tests::test_rewards_info_apy_percentage_5,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_apy_percentage_20",
        lp_tests::test_rewards_info_apy_percentage_20,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_daily_formatted",
        lp_tests::test_rewards_info_daily_formatted,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_weekly_formatted",
        lp_tests::test_rewards_info_weekly_formatted,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_monthly_formatted",
        lp_tests::test_rewards_info_monthly_formatted,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_yearly_formatted",
        lp_tests::test_rewards_info_yearly_formatted,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_small_stake",
        lp_tests::test_rewards_info_small_stake,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_large_stake",
        lp_tests::test_rewards_info_large_stake,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_zero_stake",
        lp_tests::test_rewards_info_zero_stake,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_info_zero_apy",
        lp_tests::test_rewards_info_zero_apy,
        "apps/rewards",
    ));
    suite.add(TestCase::new(
        "rewards_reward_ratio",
        lp_tests::test_rewards_reward_ratio,
        "apps/rewards",
    ));

    let (_, failed, _) = suite.run_all();
    failed == 0
}
