// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// Memory subsystem test module

mod dma;
mod helpers;
mod paging;
mod phys;
mod secure;
mod types;

use crate::test::framework::{TestCase, TestSuite};

pub fn run_all() -> bool {
    let mut suite = TestSuite::new("Memory");

    // Paging tests (65 tests)
    suite.add(TestCase::new(
        "page_size_4kib_bytes",
        paging::test_page_size_4kib_bytes,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_size_2mib_bytes",
        paging::test_page_size_2mib_bytes,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_size_1gib_bytes",
        paging::test_page_size_1gib_bytes,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_size_4kib_align_mask",
        paging::test_page_size_4kib_align_mask,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_size_2mib_align_mask",
        paging::test_page_size_2mib_align_mask,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_size_1gib_align_mask",
        paging::test_page_size_1gib_align_mask,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_size_4kib_is_aligned",
        paging::test_page_size_4kib_is_aligned,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_size_2mib_is_aligned",
        paging::test_page_size_2mib_is_aligned,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_size_1gib_is_aligned",
        paging::test_page_size_1gib_is_aligned,
        "memory/paging",
    ));
    suite.add(TestCase::new("page_size_default", paging::test_page_size_default, "memory/paging"));
    suite.add(TestCase::new(
        "page_size_equality",
        paging::test_page_size_equality,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_empty",
        paging::test_page_permissions_empty,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_from_bits",
        paging::test_page_permissions_from_bits,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_contains_read",
        paging::test_page_permissions_contains_read,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_union",
        paging::test_page_permissions_union,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_remove",
        paging::test_page_permissions_remove,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_insert",
        paging::test_page_permissions_insert,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_wx_violation",
        paging::test_page_permissions_wx_violation,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_no_wx_violation",
        paging::test_page_permissions_no_wx_violation,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_bitor",
        paging::test_page_permissions_bitor,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_bitor_assign",
        paging::test_page_permissions_bitor_assign,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_bitand",
        paging::test_page_permissions_bitand,
        "memory/paging",
    ));
    suite.add(TestCase::new("page_mapping_new", paging::test_page_mapping_new, "memory/paging"));
    suite.add(TestCase::new(
        "page_mapping_kernel",
        paging::test_page_mapping_kernel,
        "memory/paging",
    ));
    suite.add(TestCase::new("page_mapping_user", paging::test_page_mapping_user, "memory/paging"));
    suite.add(TestCase::new(
        "page_mapping_is_huge_4k",
        paging::test_page_mapping_is_huge_4k,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_mapping_is_huge_2m",
        paging::test_page_mapping_is_huge_2m,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_mapping_is_huge_1g",
        paging::test_page_mapping_is_huge_1g,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_mapping_is_shared_by_refcount",
        paging::test_page_mapping_is_shared_by_refcount,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_mapping_is_shared_by_flag",
        paging::test_page_mapping_is_shared_by_flag,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_mapping_touch",
        paging::test_page_mapping_touch,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_fault_info_from_fault",
        paging::test_page_fault_info_from_fault,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_fault_info_is_write",
        paging::test_page_fault_info_is_write,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_fault_info_is_user",
        paging::test_page_fault_info_is_user,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_fault_info_is_instruction_fetch",
        paging::test_page_fault_info_is_instruction_fetch,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_fault_info_page_was_present",
        paging::test_page_fault_info_page_was_present,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_fault_info_is_cow_fault",
        paging::test_page_fault_info_is_cow_fault,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_fault_info_is_demand_fault",
        paging::test_page_fault_info_is_demand_fault,
        "memory/paging",
    ));
    suite.add(TestCase::new("pte_flags", paging::test_pte_flags, "memory/paging"));
    suite.add(TestCase::new("pte_masks", paging::test_pte_masks, "memory/paging"));
    suite.add(TestCase::new("pte_table_flags", paging::test_pte_table_flags, "memory/paging"));
    suite.add(TestCase::new(
        "page_table_entries",
        paging::test_page_table_entries,
        "memory/paging",
    ));
    suite.add(TestCase::new("index_shifts", paging::test_index_shifts, "memory/paging"));
    suite.add(TestCase::new("index_mask", paging::test_index_mask, "memory/paging"));
    suite.add(TestCase::new("page_offset_mask", paging::test_page_offset_mask, "memory/paging"));
    suite.add(TestCase::new(
        "page_sizes_constants",
        paging::test_page_sizes_constants,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "permission_constants",
        paging::test_permission_constants,
        "memory/paging",
    ));
    suite.add(TestCase::new("pml4_index", paging::test_pml4_index, "memory/paging"));
    suite.add(TestCase::new("pdpt_index", paging::test_pdpt_index, "memory/paging"));
    suite.add(TestCase::new("pd_index", paging::test_pd_index, "memory/paging"));
    suite.add(TestCase::new("pt_index", paging::test_pt_index, "memory/paging"));
    suite.add(TestCase::new("page_offset", paging::test_page_offset, "memory/paging"));
    suite.add(TestCase::new(
        "pte_is_present_true",
        paging::test_pte_is_present_true,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "pte_is_present_false",
        paging::test_pte_is_present_false,
        "memory/paging",
    ));
    suite.add(TestCase::new("pte_is_huge_true", paging::test_pte_is_huge_true, "memory/paging"));
    suite.add(TestCase::new("pte_is_huge_false", paging::test_pte_is_huge_false, "memory/paging"));
    suite.add(TestCase::new("pte_address", paging::test_pte_address, "memory/paging"));
    suite.add(TestCase::new("page_align_down", paging::test_page_align_down, "memory/paging"));
    suite.add(TestCase::new("page_align_up", paging::test_page_align_up, "memory/paging"));
    suite.add(TestCase::new(
        "pages_needed_paging",
        paging::test_pages_needed_paging,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "paging_error_variants",
        paging::test_paging_error_variants,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "aslr_enabled_default",
        paging::test_aslr_enabled_default,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "aslr_enabled_toggle",
        paging::test_aslr_enabled_toggle,
        "memory/paging",
    ));
    suite.add(TestCase::new("page_size_clone", paging::test_page_size_clone, "memory/paging"));
    suite.add(TestCase::new(
        "page_permissions_clone",
        paging::test_page_permissions_clone,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_mapping_clone",
        paging::test_page_mapping_clone,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_fault_info_clone",
        paging::test_page_fault_info_clone,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "paging_error_clone",
        paging::test_paging_error_clone,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "page_permissions_default",
        paging::test_page_permissions_default,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "all_permission_flags",
        paging::test_all_permission_flags,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "combined_pte_flags",
        paging::test_combined_pte_flags,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "index_boundary_values",
        paging::test_index_boundary_values,
        "memory/paging",
    ));
    suite.add(TestCase::new(
        "pte_address_extraction",
        paging::test_pte_address_extraction,
        "memory/paging",
    ));

    // Physical memory tests (56 tests)
    suite.add(TestCase::new("frame_new", phys::test_frame_new, "memory/phys"));
    suite.add(TestCase::new("frame_addr", phys::test_frame_addr, "memory/phys"));
    suite.add(TestCase::new("frame_as_phys_addr", phys::test_frame_as_phys_addr, "memory/phys"));
    suite.add(TestCase::new(
        "frame_from_phys_addr",
        phys::test_frame_from_phys_addr,
        "memory/phys",
    ));
    suite.add(TestCase::new("frame_number", phys::test_frame_number, "memory/phys"));
    suite.add(TestCase::new(
        "frame_number_with_base",
        phys::test_frame_number_with_base,
        "memory/phys",
    ));
    suite.add(TestCase::new("frame_is_null", phys::test_frame_is_null, "memory/phys"));
    suite.add(TestCase::new("frame_equality", phys::test_frame_equality, "memory/phys"));
    suite.add(TestCase::new("frame_clone", phys::test_frame_clone, "memory/phys"));
    suite.add(TestCase::new("phys_frame_alias", phys::test_phys_frame_alias, "memory/phys"));
    suite.add(TestCase::new("alloc_flags_empty", phys::test_alloc_flags_empty, "memory/phys"));
    suite.add(TestCase::new("alloc_flags_zero", phys::test_alloc_flags_zero, "memory/phys"));
    suite.add(TestCase::new("alloc_flags_high", phys::test_alloc_flags_high, "memory/phys"));
    suite.add(TestCase::new("alloc_flags_dma", phys::test_alloc_flags_dma, "memory/phys"));
    suite.add(TestCase::new(
        "alloc_flags_contiguous",
        phys::test_alloc_flags_contiguous,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "alloc_flags_combined",
        phys::test_alloc_flags_combined,
        "memory/phys",
    ));
    suite.add(TestCase::new("alloc_flags_default", phys::test_alloc_flags_default, "memory/phys"));
    suite.add(TestCase::new("zone_stats_new", phys::test_zone_stats_new, "memory/phys"));
    suite.add(TestCase::new(
        "zone_stats_frames_allocated",
        phys::test_zone_stats_frames_allocated,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "zone_stats_usage_percent",
        phys::test_zone_stats_usage_percent,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "zone_stats_usage_percent_zero_total",
        phys::test_zone_stats_usage_percent_zero_total,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "zone_stats_total_bytes",
        phys::test_zone_stats_total_bytes,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "zone_stats_free_bytes",
        phys::test_zone_stats_free_bytes,
        "memory/phys",
    ));
    suite.add(TestCase::new("zone_stats_default", phys::test_zone_stats_default, "memory/phys"));
    suite.add(TestCase::new("zone_stats_clone", phys::test_zone_stats_clone, "memory/phys"));
    suite.add(TestCase::new("allocator_state_new", phys::test_allocator_state_new, "memory/phys"));
    suite.add(TestCase::new(
        "allocator_state_is_initialized_false",
        phys::test_allocator_state_is_initialized_false,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "allocator_state_default",
        phys::test_allocator_state_default,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "phys_alloc_error_variants",
        phys::test_phys_alloc_error_variants,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "phys_alloc_error_clone",
        phys::test_phys_alloc_error_clone,
        "memory/phys",
    ));
    suite.add(TestCase::new("page_size_constant", phys::test_page_size_constant, "memory/phys"));
    suite.add(TestCase::new(
        "page_size_u64_constant",
        phys::test_page_size_u64_constant,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "bits_per_byte_constant",
        phys::test_bits_per_byte_constant,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "max_physical_memory_constant",
        phys::test_max_physical_memory_constant,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "max_frame_count_constant",
        phys::test_max_frame_count_constant,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "max_bitmap_size_constant",
        phys::test_max_bitmap_size_constant,
        "memory/phys",
    ));
    suite.add(TestCase::new("align_up_zero", phys::test_align_up_zero, "memory/phys"));
    suite.add(TestCase::new("align_up_aligned", phys::test_align_up_aligned, "memory/phys"));
    suite.add(TestCase::new("align_up_unaligned", phys::test_align_up_unaligned, "memory/phys"));
    suite.add(TestCase::new(
        "align_up_zero_alignment",
        phys::test_align_up_zero_alignment,
        "memory/phys",
    ));
    suite.add(TestCase::new("align_down_zero", phys::test_align_down_zero, "memory/phys"));
    suite.add(TestCase::new("align_down_aligned", phys::test_align_down_aligned, "memory/phys"));
    suite.add(TestCase::new(
        "align_down_unaligned",
        phys::test_align_down_unaligned,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "align_down_zero_alignment",
        phys::test_align_down_zero_alignment,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "bitmap_bytes_for_frames_exact",
        phys::test_bitmap_bytes_for_frames_exact,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "bitmap_bytes_for_frames_partial",
        phys::test_bitmap_bytes_for_frames_partial,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "bitmap_bytes_for_frames_zero",
        phys::test_bitmap_bytes_for_frames_zero,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "bitmap_bytes_for_frames_large",
        phys::test_bitmap_bytes_for_frames_large,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "frames_in_range_normal",
        phys::test_frames_in_range_normal,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "frames_in_range_multiple",
        phys::test_frames_in_range_multiple,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "frames_in_range_zero",
        phys::test_frames_in_range_zero,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "frames_in_range_invalid",
        phys::test_frames_in_range_invalid,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "frames_in_range_equal",
        phys::test_frames_in_range_equal,
        "memory/phys",
    ));
    suite.add(TestCase::new("frame_copy", phys::test_frame_copy, "memory/phys"));
    suite.add(TestCase::new(
        "alloc_flags_equality",
        phys::test_alloc_flags_equality,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "zone_stats_full_allocation",
        phys::test_zone_stats_full_allocation,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "zone_stats_no_allocation",
        phys::test_zone_stats_no_allocation,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "frame_number_below_base",
        phys::test_frame_number_below_base,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "align_up_various_alignments",
        phys::test_align_up_various_alignments,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "align_down_various_alignments",
        phys::test_align_down_various_alignments,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "bitmap_bytes_for_frames_boundary",
        phys::test_bitmap_bytes_for_frames_boundary,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "alloc_flags_all_combined",
        phys::test_alloc_flags_all_combined,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "zone_stats_bytes_calculation",
        phys::test_zone_stats_bytes_calculation,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "frame_transparent_representation",
        phys::test_frame_transparent_representation,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "allocator_state_fields",
        phys::test_allocator_state_fields,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "phys_alloc_error_copy",
        phys::test_phys_alloc_error_copy,
        "memory/phys",
    ));
    suite.add(TestCase::new(
        "frames_in_range_large_range",
        phys::test_frames_in_range_large_range,
        "memory/phys",
    ));
    suite.add(TestCase::new("alloc_flags_bits", phys::test_alloc_flags_bits, "memory/phys"));

    // Secure memory tests (57 tests)
    suite.add(TestCase::new("region_type_code", secure::test_region_type_code, "memory/secure"));
    suite.add(TestCase::new("region_type_data", secure::test_region_type_data, "memory/secure"));
    suite.add(TestCase::new("region_type_stack", secure::test_region_type_stack, "memory/secure"));
    suite.add(TestCase::new("region_type_heap", secure::test_region_type_heap, "memory/secure"));
    suite.add(TestCase::new(
        "region_type_device",
        secure::test_region_type_device,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_type_capsule",
        secure::test_region_type_capsule,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_type_equality",
        secure::test_region_type_equality,
        "memory/secure",
    ));
    suite.add(TestCase::new("region_type_clone", secure::test_region_type_clone, "memory/secure"));
    suite.add(TestCase::new(
        "security_level_public",
        secure::test_security_level_public,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_internal",
        secure::test_security_level_internal,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_confidential",
        secure::test_security_level_confidential,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_secret",
        secure::test_security_level_secret,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_top_secret",
        secure::test_security_level_top_secret,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_ordering",
        secure::test_security_level_ordering,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_equality",
        secure::test_security_level_equality,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_clone",
        secure::test_security_level_clone,
        "memory/secure",
    ));
    suite.add(TestCase::new("memory_region_new", secure::test_memory_region_new, "memory/secure"));
    suite.add(TestCase::new(
        "memory_region_encrypted_secret",
        secure::test_memory_region_encrypted_secret,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_encrypted_top_secret",
        secure::test_memory_region_encrypted_top_secret,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_not_encrypted_public",
        secure::test_memory_region_not_encrypted_public,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_end_addr",
        secure::test_memory_region_end_addr,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_contains_inside",
        secure::test_memory_region_contains_inside,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_contains_outside",
        secure::test_memory_region_contains_outside,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_page_count_single",
        secure::test_memory_region_page_count_single,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_page_count_multiple",
        secure::test_memory_region_page_count_multiple,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_page_count_partial",
        secure::test_memory_region_page_count_partial,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_clone",
        secure::test_memory_region_clone,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "manager_stats_utilization_percent",
        secure::test_manager_stats_utilization_percent,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "manager_stats_utilization_percent_zero_peak",
        secure::test_manager_stats_utilization_percent_zero_peak,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "manager_stats_clone",
        secure::test_manager_stats_clone,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "secure_memory_error_variants",
        secure::test_secure_memory_error_variants,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "secure_memory_error_clone",
        secure::test_secure_memory_error_clone,
        "memory/secure",
    ));
    suite.add(TestCase::new("limits_constants", secure::test_limits_constants, "memory/secure"));
    suite.add(TestCase::new("scrub_constants", secure::test_scrub_constants, "memory/secure"));
    suite.add(TestCase::new("max_constants", secure::test_max_constants, "memory/secure"));
    suite.add(TestCase::new(
        "process_id_constants",
        secure::test_process_id_constants,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "permission_constants",
        secure::test_permission_constants,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_constants",
        secure::test_security_level_constants,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "encryption_threshold",
        secure::test_encryption_threshold,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_type_constants",
        secure::test_region_type_constants,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_id_constants",
        secure::test_region_id_constants,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_all_variants",
        secure::test_security_level_all_variants,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_type_same_value",
        secure::test_region_type_same_value,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_same_value",
        secure::test_security_level_same_value,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_large_size",
        secure::test_memory_region_large_size,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_type_all_writable",
        secure::test_region_type_all_writable,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_type_all_not_writable",
        secure::test_region_type_all_not_writable,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_type_all_executable",
        secure::test_region_type_all_executable,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "region_type_all_not_executable",
        secure::test_region_type_all_not_executable,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "manager_stats_fields",
        secure::test_manager_stats_fields,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "memory_region_boundary_address",
        secure::test_memory_region_boundary_address,
        "memory/secure",
    ));
    suite.add(TestCase::new(
        "security_level_copy",
        secure::test_security_level_copy,
        "memory/secure",
    ));
    suite.add(TestCase::new("region_type_copy", secure::test_region_type_copy, "memory/secure"));

    // Memory types/layout tests (55 tests)
    suite.add(TestCase::new(
        "memory_protection_none",
        types::test_memory_protection_none,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_protection_read",
        types::test_memory_protection_read,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_protection_read_write",
        types::test_memory_protection_read_write,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_protection_read_execute",
        types::test_memory_protection_read_execute,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_protection_equality",
        types::test_memory_protection_equality,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_protection_clone",
        types::test_memory_protection_clone,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_protection_copy",
        types::test_memory_protection_copy,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_type_anonymous",
        types::test_memory_type_anonymous,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_type_kernel_code",
        types::test_memory_type_kernel_code,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_type_kernel_data",
        types::test_memory_type_kernel_data,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_type_user_code",
        types::test_memory_type_user_code,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_type_user_data",
        types::test_memory_type_user_data,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_type_user_heap",
        types::test_memory_type_user_heap,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_type_user_stack",
        types::test_memory_type_user_stack,
        "memory/types",
    ));
    suite.add(TestCase::new("memory_type_device", types::test_memory_type_device, "memory/types"));
    suite.add(TestCase::new(
        "memory_type_secure_capsule",
        types::test_memory_type_secure_capsule,
        "memory/types",
    ));
    suite.add(TestCase::new("memory_type_shared", types::test_memory_type_shared, "memory/types"));
    suite.add(TestCase::new(
        "memory_type_equality",
        types::test_memory_type_equality,
        "memory/types",
    ));
    suite.add(TestCase::new("memory_type_clone", types::test_memory_type_clone, "memory/types"));
    suite.add(TestCase::new("memory_type_copy", types::test_memory_type_copy, "memory/types"));
    suite.add(TestCase::new(
        "region_kind_available",
        types::test_region_kind_available,
        "memory/types",
    ));
    suite.add(TestCase::new("region_kind_usable", types::test_region_kind_usable, "memory/types"));
    suite.add(TestCase::new(
        "region_kind_reserved",
        types::test_region_kind_reserved,
        "memory/types",
    ));
    suite.add(TestCase::new("region_kind_acpi", types::test_region_kind_acpi, "memory/types"));
    suite.add(TestCase::new("region_kind_mmio", types::test_region_kind_mmio, "memory/types"));
    suite.add(TestCase::new("region_kind_kernel", types::test_region_kind_kernel, "memory/types"));
    suite.add(TestCase::new("region_kind_boot", types::test_region_kind_boot, "memory/types"));
    suite.add(TestCase::new(
        "region_kind_unknown",
        types::test_region_kind_unknown,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "region_kind_equality",
        types::test_region_kind_equality,
        "memory/types",
    ));
    suite.add(TestCase::new("region_kind_clone", types::test_region_kind_clone, "memory/types"));
    suite.add(TestCase::new("region_kind_copy", types::test_region_kind_copy, "memory/types"));
    suite.add(TestCase::new(
        "layout_error_slide_not_aligned",
        types::test_layout_error_slide_not_aligned,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_kernel_base_too_low",
        types::test_layout_error_kernel_base_too_low,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_percpu_stride_misaligned",
        types::test_layout_error_percpu_stride_misaligned,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_window_overlap",
        types::test_layout_error_window_overlap,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_order_violation",
        types::test_layout_error_order_violation,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_size_exceeds_capacity",
        types::test_layout_error_size_exceeds_capacity,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_not_in_kernel_space",
        types::test_layout_error_not_in_kernel_space,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_not_in_user_space",
        types::test_layout_error_not_in_user_space,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_invalid_alignment",
        types::test_layout_error_invalid_alignment,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_not_initialized",
        types::test_layout_error_not_initialized,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_config_locked",
        types::test_layout_error_config_locked,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_invalid_region_bounds",
        types::test_layout_error_invalid_region_bounds,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_equality",
        types::test_layout_error_equality,
        "memory/types",
    ));
    suite.add(TestCase::new("layout_error_clone", types::test_layout_error_clone, "memory/types"));
    suite.add(TestCase::new("layout_error_copy", types::test_layout_error_copy, "memory/types"));
    suite.add(TestCase::new(
        "page_size_constant_types",
        types::test_page_size_constant,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "page_size_u64_constant_types",
        types::test_page_size_u64_constant,
        "memory/types",
    ));
    suite.add(TestCase::new("page_mask_constant", types::test_page_mask_constant, "memory/types"));
    suite.add(TestCase::new(
        "huge_page_2m_constant",
        types::test_huge_page_2m_constant,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "huge_page_1g_constant",
        types::test_huge_page_1g_constant,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "directmap_base_constant",
        types::test_directmap_base_constant,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "directmap_size_constant",
        types::test_directmap_size_constant,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "kheap_base_constant",
        types::test_kheap_base_constant,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "kheap_size_constant",
        types::test_kheap_size_constant,
        "memory/types",
    ));
    suite.add(TestCase::new("kvm_base_constant", types::test_kvm_base_constant, "memory/types"));
    suite.add(TestCase::new("kvm_size_constant", types::test_kvm_size_constant, "memory/types"));
    suite.add(TestCase::new(
        "max_phys_addr_constant",
        types::test_max_phys_addr_constant,
        "memory/types",
    ));
    suite.add(TestCase::new("max_cpus_constant", types::test_max_cpus_constant, "memory/types"));
    suite.add(TestCase::new("page_alignment", types::test_page_alignment, "memory/types"));
    suite.add(TestCase::new("page_offset_types", types::test_page_offset, "memory/types"));
    suite.add(TestCase::new(
        "huge_page_sizes_ordering",
        types::test_huge_page_sizes_ordering,
        "memory/types",
    ));
    suite.add(TestCase::new("region_sizes_valid", types::test_region_sizes_valid, "memory/types"));
    suite.add(TestCase::new(
        "memory_type_all_variants",
        types::test_memory_type_all_variants,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "memory_protection_all_variants",
        types::test_memory_protection_all_variants,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "region_kind_all_have_str",
        types::test_region_kind_all_have_str,
        "memory/types",
    ));
    suite.add(TestCase::new(
        "layout_error_all_variants",
        types::test_layout_error_all_variants,
        "memory/types",
    ));

    // Buddy allocator helper tests (46 tests)
    suite.add(TestCase::new(
        "max_order_constant",
        helpers::test_max_order_constant,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "min_order_constant",
        helpers::test_min_order_constant,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "free_list_count_constant",
        helpers::test_free_list_count_constant,
        "memory/helpers",
    ));
    suite.add(TestCase::new("alloc_flag_zero", helpers::test_alloc_flag_zero, "memory/helpers"));
    suite.add(TestCase::new("alloc_flag_dma", helpers::test_alloc_flag_dma, "memory/helpers"));
    suite.add(TestCase::new(
        "alloc_flag_uncached",
        helpers::test_alloc_flag_uncached,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_flag_write_combine",
        helpers::test_alloc_flag_write_combine,
        "memory/helpers",
    ));
    suite.add(TestCase::new("alloc_flag_user", helpers::test_alloc_flag_user, "memory/helpers"));
    suite.add(TestCase::new("alloc_flag_exec", helpers::test_alloc_flag_exec, "memory/helpers"));
    suite.add(TestCase::new(
        "alloc_flags_unique",
        helpers::test_alloc_flags_unique,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_flags_powers_of_two",
        helpers::test_alloc_flags_powers_of_two,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_flags_combinable",
        helpers::test_alloc_flags_combinable,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "order_to_size_min",
        helpers::test_order_to_size_min,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "order_to_size_max",
        helpers::test_order_to_size_max,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "order_to_size_various",
        helpers::test_order_to_size_various,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "order_to_size_zero",
        helpers::test_order_to_size_zero,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "size_to_order_exact",
        helpers::test_size_to_order_exact,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "size_to_order_non_power_of_two",
        helpers::test_size_to_order_non_power_of_two,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "size_to_order_small",
        helpers::test_size_to_order_small,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "size_to_order_large",
        helpers::test_size_to_order_large,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "order_to_size_roundtrip",
        helpers::test_order_to_size_roundtrip,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "buddy_address_order_12",
        helpers::test_buddy_address_order_12,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "buddy_address_order_13",
        helpers::test_buddy_address_order_13,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "buddy_address_xor_property",
        helpers::test_buddy_address_xor_property,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "buddy_address_different_orders",
        helpers::test_buddy_address_different_orders,
        "memory/helpers",
    ));
    suite.add(TestCase::new("alloc_stats_new", helpers::test_alloc_stats_new, "memory/helpers"));
    suite.add(TestCase::new(
        "alloc_stats_free_memory",
        helpers::test_alloc_stats_free_memory,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_stats_free_memory_zero_allocated",
        helpers::test_alloc_stats_free_memory_zero_allocated,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_stats_free_memory_full",
        helpers::test_alloc_stats_free_memory_full,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_stats_clone",
        helpers::test_alloc_stats_clone,
        "memory/helpers",
    ));
    suite.add(TestCase::new("alloc_stats_copy", helpers::test_alloc_stats_copy, "memory/helpers"));
    suite.add(TestCase::new(
        "alloc_stats_default",
        helpers::test_alloc_stats_default,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "order_range_valid",
        helpers::test_order_range_valid,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "buddy_address_aligned",
        helpers::test_buddy_address_aligned,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_flags_all_combined_helpers",
        helpers::test_alloc_flags_all_combined,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "order_to_size_powers_of_two",
        helpers::test_order_to_size_powers_of_two,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "size_to_order_zero",
        helpers::test_size_to_order_zero,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "buddy_address_zero",
        helpers::test_buddy_address_zero,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_stats_fields_modification",
        helpers::test_alloc_stats_fields_modification,
        "memory/helpers",
    ));
    suite.add(TestCase::new("order_boundaries", helpers::test_order_boundaries, "memory/helpers"));
    suite.add(TestCase::new(
        "buddy_address_large",
        helpers::test_buddy_address_large,
        "memory/helpers",
    ));
    suite.add(TestCase::new(
        "alloc_stats_utilization",
        helpers::test_alloc_stats_utilization,
        "memory/helpers",
    ));
    suite.add(TestCase::new("flag_isolation", helpers::test_flag_isolation, "memory/helpers"));
    suite.add(TestCase::new(
        "order_to_size_consistency",
        helpers::test_order_to_size_consistency,
        "memory/helpers",
    ));
    suite.add(TestCase::new("buddy_pairs", helpers::test_buddy_pairs, "memory/helpers"));

    // DMA tests (63 tests)
    suite.add(TestCase::new(
        "dma_direction_to_device",
        dma::test_dma_direction_to_device,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_direction_from_device",
        dma::test_dma_direction_from_device,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_direction_bidirectional",
        dma::test_dma_direction_bidirectional,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_direction_default",
        dma::test_dma_direction_default,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_direction_equality",
        dma::test_dma_direction_equality,
        "memory/dma",
    ));
    suite.add(TestCase::new("dma_direction_clone", dma::test_dma_direction_clone, "memory/dma"));
    suite.add(TestCase::new("dma_direction_copy", dma::test_dma_direction_copy, "memory/dma"));
    suite.add(TestCase::new("dma_constraints_new", dma::test_dma_constraints_new, "memory/dma"));
    suite.add(TestCase::new(
        "dma_constraints_dma32",
        dma::test_dma_constraints_dma32,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_constraints_non_coherent",
        dma::test_dma_constraints_non_coherent,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_constraints_default",
        dma::test_dma_constraints_default,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_constraints_clone",
        dma::test_dma_constraints_clone,
        "memory/dma",
    ));
    suite.add(TestCase::new("dma_constraints_copy", dma::test_dma_constraints_copy, "memory/dma"));
    suite.add(TestCase::new("dma_region_new", dma::test_dma_region_new, "memory/dma"));
    suite.add(TestCase::new("dma_region_dma_addr", dma::test_dma_region_dma_addr, "memory/dma"));
    suite.add(TestCase::new("dma_region_as_ptr", dma::test_dma_region_as_ptr, "memory/dma"));
    suite.add(TestCase::new(
        "dma_region_as_mut_ptr",
        dma::test_dma_region_as_mut_ptr,
        "memory/dma",
    ));
    suite.add(TestCase::new("dma_region_clone", dma::test_dma_region_clone, "memory/dma"));
    suite.add(TestCase::new("dma_region_copy", dma::test_dma_region_copy, "memory/dma"));
    suite.add(TestCase::new(
        "streaming_mapping_new",
        dma::test_streaming_mapping_new,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "streaming_mapping_with_bounce",
        dma::test_streaming_mapping_with_bounce,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "streaming_mapping_dma_address",
        dma::test_streaming_mapping_dma_address,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "streaming_mapping_clone",
        dma::test_streaming_mapping_clone,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "streaming_mapping_copy",
        dma::test_streaming_mapping_copy,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_stats_snapshot_new",
        dma::test_dma_stats_snapshot_new,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_stats_snapshot_default",
        dma::test_dma_stats_snapshot_default,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_stats_snapshot_clone",
        dma::test_dma_stats_snapshot_clone,
        "memory/dma",
    ));
    suite.add(TestCase::new("dma_error_as_str", dma::test_dma_error_as_str, "memory/dma"));
    suite.add(TestCase::new("dma_error_is_fatal", dma::test_dma_error_is_fatal, "memory/dma"));
    suite.add(TestCase::new("dma_error_is_bug", dma::test_dma_error_is_bug, "memory/dma"));
    suite.add(TestCase::new(
        "dma_error_is_recoverable",
        dma::test_dma_error_is_recoverable,
        "memory/dma",
    ));
    suite.add(TestCase::new("dma_error_equality", dma::test_dma_error_equality, "memory/dma"));
    suite.add(TestCase::new("dma_error_clone", dma::test_dma_error_clone, "memory/dma"));
    suite.add(TestCase::new("dma_error_copy", dma::test_dma_error_copy, "memory/dma"));
    suite.add(TestCase::new(
        "default_alignment_constant",
        dma::test_default_alignment_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "default_max_segment_size_constant",
        dma::test_default_max_segment_size_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new("dma32_limit_constant", dma::test_dma32_limit_constant, "memory/dma"));
    suite.add(TestCase::new(
        "min_dma_size_constant",
        dma::test_min_dma_size_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "max_dma_size_constant",
        dma::test_max_dma_size_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "pte_dma_coherent_constant",
        dma::test_pte_dma_coherent_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "pte_cache_disable_constant",
        dma::test_pte_cache_disable_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "pte_dma_non_coherent_constant",
        dma::test_pte_dma_non_coherent_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "default_pool_region_size_constant",
        dma::test_default_pool_region_size_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "max_pool_capacity_constant",
        dma::test_max_pool_capacity_constant,
        "memory/dma",
    ));
    suite.add(TestCase::new("align_up_zero_dma", dma::test_align_up_zero, "memory/dma"));
    suite.add(TestCase::new("align_up_aligned_dma", dma::test_align_up_aligned, "memory/dma"));
    suite.add(TestCase::new("align_up_unaligned_dma", dma::test_align_up_unaligned, "memory/dma"));
    suite.add(TestCase::new("align_down_zero_dma", dma::test_align_down_zero, "memory/dma"));
    suite.add(TestCase::new("align_down_aligned_dma", dma::test_align_down_aligned, "memory/dma"));
    suite.add(TestCase::new(
        "align_down_unaligned_dma",
        dma::test_align_down_unaligned,
        "memory/dma",
    ));
    suite.add(TestCase::new("is_aligned_true", dma::test_is_aligned_true, "memory/dma"));
    suite.add(TestCase::new("is_aligned_false", dma::test_is_aligned_false, "memory/dma"));
    suite.add(TestCase::new("pages_needed_zero_dma", dma::test_pages_needed_zero, "memory/dma"));
    suite.add(TestCase::new("pages_needed_exact_dma", dma::test_pages_needed_exact, "memory/dma"));
    suite.add(TestCase::new(
        "pages_needed_partial_dma",
        dma::test_pages_needed_partial,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "is_dma32_compatible_true",
        dma::test_is_dma32_compatible_true,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "is_dma32_compatible_false",
        dma::test_is_dma32_compatible_false,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "is_range_dma32_compatible_true",
        dma::test_is_range_dma32_compatible_true,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "is_range_dma32_compatible_false",
        dma::test_is_range_dma32_compatible_false,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_error_all_variants",
        dma::test_dma_error_all_variants,
        "memory/dma",
    ));
    suite.add(TestCase::new(
        "dma_direction_all_variants",
        dma::test_dma_direction_all_variants,
        "memory/dma",
    ));

    let (_, failed, _) = suite.run_all();
    failed == 0
}
