// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

mod copy;
mod error;
mod validate;

use crate::test::framework::{TestCase, TestSuite};

pub fn run_all() -> bool {
    let mut suite = TestSuite::new("usercopy");

    // Copy tests (3)
    suite.add(TestCase::new("module_exists", copy::test_module_exists));
    suite.add(TestCase::new("basic_constants", copy::test_basic_constants));
    suite.add(TestCase::new("basic_operations", copy::test_basic_operations));

    // Error tests (31)
    suite.add(TestCase::new(
        "usercopy_error_null_pointer_variant",
        error::test_usercopy_error_null_pointer_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_invalid_address_variant",
        error::test_usercopy_error_invalid_address_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_address_overflow_variant",
        error::test_usercopy_error_address_overflow_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_page_not_mapped_variant",
        error::test_usercopy_error_page_not_mapped_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_page_not_user_variant",
        error::test_usercopy_error_page_not_user_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_page_not_writable_variant",
        error::test_usercopy_error_page_not_writable_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_page_fault_variant",
        error::test_usercopy_error_page_fault_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_no_process_context_variant",
        error::test_usercopy_error_no_process_context_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_size_too_large_variant",
        error::test_usercopy_error_size_too_large_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_variants_not_equal",
        error::test_usercopy_error_variants_not_equal,
    ));
    suite.add(TestCase::new("usercopy_error_clone", error::test_usercopy_error_clone));
    suite.add(TestCase::new("usercopy_error_copy", error::test_usercopy_error_copy));
    suite.add(TestCase::new(
        "usercopy_error_display_null_pointer",
        error::test_usercopy_error_display_null_pointer,
    ));
    suite.add(TestCase::new(
        "usercopy_error_display_invalid_address",
        error::test_usercopy_error_display_invalid_address,
    ));
    suite.add(TestCase::new(
        "usercopy_error_display_address_overflow",
        error::test_usercopy_error_display_address_overflow,
    ));
    suite.add(TestCase::new(
        "usercopy_error_display_page_not_mapped",
        error::test_usercopy_error_display_page_not_mapped,
    ));
    suite.add(TestCase::new(
        "usercopy_error_display_page_not_user",
        error::test_usercopy_error_display_page_not_user,
    ));
    suite.add(TestCase::new(
        "usercopy_error_display_page_not_writable",
        error::test_usercopy_error_display_page_not_writable,
    ));
    suite.add(TestCase::new(
        "usercopy_error_display_page_fault",
        error::test_usercopy_error_display_page_fault,
    ));
    suite.add(TestCase::new(
        "usercopy_error_display_no_process_context",
        error::test_usercopy_error_display_no_process_context,
    ));
    suite.add(TestCase::new(
        "usercopy_error_display_size_too_large",
        error::test_usercopy_error_display_size_too_large,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_null_pointer",
        error::test_usercopy_error_debug_null_pointer,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_invalid_address",
        error::test_usercopy_error_debug_invalid_address,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_address_overflow",
        error::test_usercopy_error_debug_address_overflow,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_page_not_mapped",
        error::test_usercopy_error_debug_page_not_mapped,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_page_not_user",
        error::test_usercopy_error_debug_page_not_user,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_page_not_writable",
        error::test_usercopy_error_debug_page_not_writable,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_page_fault",
        error::test_usercopy_error_debug_page_fault,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_no_process_context",
        error::test_usercopy_error_debug_no_process_context,
    ));
    suite.add(TestCase::new(
        "usercopy_error_debug_size_too_large",
        error::test_usercopy_error_debug_size_too_large,
    ));
    suite.add(TestCase::new(
        "usercopy_error_equality_same_variant",
        error::test_usercopy_error_equality_same_variant,
    ));
    suite.add(TestCase::new(
        "usercopy_error_all_variants_unique_display",
        error::test_usercopy_error_all_variants_unique_display,
    ));
    suite.add(TestCase::new("usercopy_error_result_ok", error::test_usercopy_error_result_ok));
    suite.add(TestCase::new("usercopy_error_result_err", error::test_usercopy_error_result_err));
    suite.add(TestCase::new(
        "usercopy_error_match_exhaustive",
        error::test_usercopy_error_match_exhaustive,
    ));

    // Validate tests (48)
    suite.add(TestCase::new(
        "validate_user_read_null_pointer",
        validate::test_validate_user_read_null_pointer,
    ));
    suite.add(TestCase::new(
        "validate_user_write_null_pointer",
        validate::test_validate_user_write_null_pointer,
    ));
    suite.add(TestCase::new(
        "validate_user_read_zero_length",
        validate::test_validate_user_read_zero_length,
    ));
    suite.add(TestCase::new(
        "validate_user_write_zero_length",
        validate::test_validate_user_write_zero_length,
    ));
    suite.add(TestCase::new(
        "validate_user_read_size_too_large",
        validate::test_validate_user_read_size_too_large,
    ));
    suite.add(TestCase::new(
        "validate_user_write_size_too_large",
        validate::test_validate_user_write_size_too_large,
    ));
    suite.add(TestCase::new(
        "validate_user_read_max_copy_size_exact",
        validate::test_validate_user_read_max_copy_size_exact,
    ));
    suite.add(TestCase::new(
        "validate_user_write_max_copy_size_exact",
        validate::test_validate_user_write_max_copy_size_exact,
    ));
    suite.add(TestCase::new(
        "validate_user_read_address_overflow",
        validate::test_validate_user_read_address_overflow,
    ));
    suite.add(TestCase::new(
        "validate_user_write_address_overflow",
        validate::test_validate_user_write_address_overflow,
    ));
    suite.add(TestCase::new(
        "validate_user_read_address_overflow_boundary",
        validate::test_validate_user_read_address_overflow_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_write_address_overflow_boundary",
        validate::test_validate_user_write_address_overflow_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_read_kernel_space_start",
        validate::test_validate_user_read_kernel_space_start,
    ));
    suite.add(TestCase::new(
        "validate_user_write_kernel_space_start",
        validate::test_validate_user_write_kernel_space_start,
    ));
    suite.add(TestCase::new(
        "validate_user_read_kernel_space_high",
        validate::test_validate_user_read_kernel_space_high,
    ));
    suite.add(TestCase::new(
        "validate_user_write_kernel_space_high",
        validate::test_validate_user_write_kernel_space_high,
    ));
    suite.add(TestCase::new(
        "validate_user_read_non_canonical_address",
        validate::test_validate_user_read_non_canonical_address,
    ));
    suite.add(TestCase::new(
        "validate_user_write_non_canonical_address",
        validate::test_validate_user_write_non_canonical_address,
    ));
    suite.add(TestCase::new(
        "validate_user_read_user_space_end_boundary",
        validate::test_validate_user_read_user_space_end_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_write_user_space_end_boundary",
        validate::test_validate_user_write_user_space_end_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_read_crosses_user_space_boundary",
        validate::test_validate_user_read_crosses_user_space_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_write_crosses_user_space_boundary",
        validate::test_validate_user_write_crosses_user_space_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_read_valid_low_address",
        validate::test_validate_user_read_valid_low_address,
    ));
    suite.add(TestCase::new(
        "validate_user_write_valid_low_address",
        validate::test_validate_user_write_valid_low_address,
    ));
    suite.add(TestCase::new(
        "validate_user_read_page_aligned_address",
        validate::test_validate_user_read_page_aligned_address,
    ));
    suite.add(TestCase::new(
        "validate_user_write_page_aligned_address",
        validate::test_validate_user_write_page_aligned_address,
    ));
    suite.add(TestCase::new(
        "validate_user_read_non_page_aligned_address",
        validate::test_validate_user_read_non_page_aligned_address,
    ));
    suite.add(TestCase::new(
        "validate_user_write_non_page_aligned_address",
        validate::test_validate_user_write_non_page_aligned_address,
    ));
    suite.add(TestCase::new(
        "validate_user_read_crossing_page_boundary",
        validate::test_validate_user_read_crossing_page_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_write_crossing_page_boundary",
        validate::test_validate_user_write_crossing_page_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_read_multiple_pages",
        validate::test_validate_user_read_multiple_pages,
    ));
    suite.add(TestCase::new(
        "validate_user_write_multiple_pages",
        validate::test_validate_user_write_multiple_pages,
    ));
    suite.add(TestCase::new(
        "validate_user_read_single_byte",
        validate::test_validate_user_read_single_byte,
    ));
    suite.add(TestCase::new(
        "validate_user_write_single_byte",
        validate::test_validate_user_write_single_byte,
    ));
    suite.add(TestCase::new(
        "validate_user_read_large_valid_size",
        validate::test_validate_user_read_large_valid_size,
    ));
    suite.add(TestCase::new(
        "validate_user_write_large_valid_size",
        validate::test_validate_user_write_large_valid_size,
    ));
    suite.add(TestCase::new(
        "validate_user_read_end_exactly_at_boundary",
        validate::test_validate_user_read_end_exactly_at_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_write_end_exactly_at_boundary",
        validate::test_validate_user_write_end_exactly_at_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_read_address_one",
        validate::test_validate_user_read_address_one,
    ));
    suite.add(TestCase::new(
        "validate_user_write_address_one",
        validate::test_validate_user_write_address_one,
    ));
    suite.add(TestCase::new(
        "validate_user_read_hole_address",
        validate::test_validate_user_read_hole_address,
    ));
    suite.add(TestCase::new(
        "validate_user_write_hole_address",
        validate::test_validate_user_write_hole_address,
    ));
    suite.add(TestCase::new(
        "validate_user_read_just_above_user_space",
        validate::test_validate_user_read_just_above_user_space,
    ));
    suite.add(TestCase::new(
        "validate_user_write_just_above_user_space",
        validate::test_validate_user_write_just_above_user_space,
    ));
    suite.add(TestCase::new(
        "validate_user_read_wrapping_length",
        validate::test_validate_user_read_wrapping_length,
    ));
    suite.add(TestCase::new(
        "validate_user_write_wrapping_length",
        validate::test_validate_user_write_wrapping_length,
    ));
    suite.add(TestCase::new(
        "validate_user_read_mid_range_address",
        validate::test_validate_user_read_mid_range_address,
    ));
    suite.add(TestCase::new(
        "validate_user_write_mid_range_address",
        validate::test_validate_user_write_mid_range_address,
    ));
    suite.add(TestCase::new(
        "validate_user_read_exact_page_size",
        validate::test_validate_user_read_exact_page_size,
    ));
    suite.add(TestCase::new(
        "validate_user_write_exact_page_size",
        validate::test_validate_user_write_exact_page_size,
    ));
    suite.add(TestCase::new(
        "validate_user_read_typical_stack_address",
        validate::test_validate_user_read_typical_stack_address,
    ));
    suite.add(TestCase::new(
        "validate_user_write_typical_stack_address",
        validate::test_validate_user_write_typical_stack_address,
    ));
    suite.add(TestCase::new(
        "validate_user_read_typical_heap_address",
        validate::test_validate_user_read_typical_heap_address,
    ));
    suite.add(TestCase::new(
        "validate_user_write_typical_heap_address",
        validate::test_validate_user_write_typical_heap_address,
    ));
    suite.add(TestCase::new(
        "validate_user_read_negative_canonical_boundary",
        validate::test_validate_user_read_negative_canonical_boundary,
    ));
    suite.add(TestCase::new(
        "validate_user_write_negative_canonical_boundary",
        validate::test_validate_user_write_negative_canonical_boundary,
    ));

    suite.run()
}
