// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// WiFi driver test suite - 132 tests across 3 modules

pub mod constants;
pub mod error;
pub mod scan;

use crate::test::framework::{TestCase, TestSuite};

/// Run all WiFi driver tests.
/// Returns true if all tests pass.
pub fn run_all() -> bool {
    let mut suite = TestSuite::new("WiFi Driver");

    // Constants tests - 50 tests
    suite.add(TestCase::with_category(
        "intel_vendor_id",
        constants::test_intel_vendor_id,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "supported_device_ids_not_empty",
        constants::test_supported_device_ids_not_empty,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "ax210_device_id",
        constants::test_ax210_device_id,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "ax200_device_id",
        constants::test_ax200_device_id,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "ac8265_device_id",
        constants::test_ac8265_device_id,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "wireless_n_device_id",
        constants::test_wireless_n_device_id,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "csr_hw_if_config",
        constants::test_csr_hw_if_config,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "csr_int",
        constants::test_csr_int,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "csr_int_mask",
        constants::test_csr_int_mask,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "csr_reset",
        constants::test_csr_reset,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "csr_gp_cntrl",
        constants::test_csr_gp_cntrl,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "csr_hw_rev",
        constants::test_csr_hw_rev,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "gp_cntrl_mac_access_ena",
        constants::test_gp_cntrl_mac_access_ena,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "gp_cntrl_mac_clock_ready",
        constants::test_gp_cntrl_mac_clock_ready,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "gp_cntrl_init_done",
        constants::test_gp_cntrl_init_done,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "gp_cntrl_mac_access_req",
        constants::test_gp_cntrl_mac_access_req,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "reset_sw_reset",
        constants::test_reset_sw_reset,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "reset_stop_master",
        constants::test_reset_stop_master,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "int_bit_fh_rx",
        constants::test_int_bit_fh_rx,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "int_bit_hw_err",
        constants::test_int_bit_hw_err,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "int_bit_rf_kill",
        constants::test_int_bit_rf_kill,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "int_bit_alive",
        constants::test_int_bit_alive,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "num_tfd_queues",
        constants::test_num_tfd_queues,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "tfd_queue_size_log",
        constants::test_tfd_queue_size_log,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "tfd_queue_size",
        constants::test_tfd_queue_size,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "tfd_queue_size_mask",
        constants::test_tfd_queue_size_mask,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "rx_queue_size",
        constants::test_rx_queue_size,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "rx_buffer_size",
        constants::test_rx_buffer_size,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "tx_buffer_size",
        constants::test_tx_buffer_size,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "max_cmd_payload_size",
        constants::test_max_cmd_payload_size,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "alive_timeout",
        constants::test_alive_timeout,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "init_timeout",
        constants::test_init_timeout,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "scan_timeout",
        constants::test_scan_timeout,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "connect_timeout",
        constants::test_connect_timeout,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "apm_init_timeout",
        constants::test_apm_init_timeout,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "nic_access_timeout",
        constants::test_nic_access_timeout,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "dma_alignment",
        constants::test_dma_alignment,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "tfd_alignment",
        constants::test_tfd_alignment,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "rssi_invalid",
        constants::test_rssi_invalid,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "fw_api_version_range",
        constants::test_fw_api_version_range,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "iwl_fw_magic",
        constants::test_iwl_fw_magic,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "all_ints_mask",
        constants::test_all_ints_mask,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "int_mask_disabled",
        constants::test_int_mask_disabled,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "cmd_mvm_alive",
        constants::test_cmd_mvm_alive,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "cmd_reply_error",
        constants::test_cmd_reply_error,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "cmd_tx_cmd",
        constants::test_cmd_tx_cmd,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "cmd_scan_req_umac",
        constants::test_cmd_scan_req_umac,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "cmd_add_sta",
        constants::test_cmd_add_sta,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "queue_sizes_power_of_two",
        constants::test_queue_sizes_power_of_two,
        "drivers/wifi/constants",
    ));
    suite.add(TestCase::with_category(
        "buffer_sizes_power_of_two",
        constants::test_buffer_sizes_power_of_two,
        "drivers/wifi/constants",
    ));

    // Error tests - 38 tests
    suite.add(TestCase::with_category(
        "error_not_initialized",
        error::test_error_not_initialized,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_device_not_found",
        error::test_error_device_not_found,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_firmware_not_found",
        error::test_error_firmware_not_found,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_firmware_invalid",
        error::test_error_firmware_invalid,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_firmware_load_failed",
        error::test_error_firmware_load_failed,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_hardware_error",
        error::test_error_hardware_error,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_timeout",
        error::test_error_timeout,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_invalid_state",
        error::test_error_invalid_state,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_not_connected",
        error::test_error_not_connected,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_authentication_failed",
        error::test_error_authentication_failed,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_association_failed",
        error::test_error_association_failed,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_scan_failed",
        error::test_error_scan_failed,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_no_network",
        error::test_error_no_network,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_invalid_parameter",
        error::test_error_invalid_parameter,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_buffer_too_small",
        error::test_error_buffer_too_small,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_dma_error",
        error::test_error_dma_error,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_command_failed",
        error::test_error_command_failed,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_rf_kill",
        error::test_error_rf_kill,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_nvm_error",
        error::test_error_nvm_error,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_out_of_memory",
        error::test_error_out_of_memory,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_invalid_frame",
        error::test_error_invalid_frame,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_invalid_key",
        error::test_error_invalid_key,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_mic_failure",
        error::test_error_mic_failure,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_replay_attack",
        error::test_error_replay_attack,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_integrity_failure",
        error::test_error_integrity_failure,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_unsupported_security",
        error::test_error_unsupported_security,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_handshake_timeout",
        error::test_error_handshake_timeout,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_handshake_failed",
        error::test_error_handshake_failed,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_decryption_failed",
        error::test_error_decryption_failed,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_firmware_timeout",
        error::test_error_firmware_timeout,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_network_not_found",
        error::test_error_network_not_found,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_equality",
        error::test_error_equality,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category("error_copy", error::test_error_copy, "drivers/wifi/error"));
    suite.add(TestCase::with_category(
        "error_clone",
        error::test_error_clone,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_debug",
        error::test_error_debug,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_display",
        error::test_error_display,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "error_codes_unique",
        error::test_error_codes_unique,
        "drivers/wifi/error",
    ));
    suite.add(TestCase::with_category(
        "all_errors_have_message",
        error::test_all_errors_have_message,
        "drivers/wifi/error",
    ));

    // Scan tests - 44 tests
    suite.add(TestCase::with_category(
        "security_type_open_str",
        scan::test_security_type_open_str,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_wep_str",
        scan::test_security_type_wep_str,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_wpa_psk_str",
        scan::test_security_type_wpa_psk_str,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_wpa2_psk_str",
        scan::test_security_type_wpa2_psk_str,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_wpa3_sae_str",
        scan::test_security_type_wpa3_sae_str,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_enterprise_str",
        scan::test_security_type_enterprise_str,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_unknown_str",
        scan::test_security_type_unknown_str,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_open_no_password",
        scan::test_security_type_open_no_password,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_wep_requires_password",
        scan::test_security_type_wep_requires_password,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_wpa_psk_requires_password",
        scan::test_security_type_wpa_psk_requires_password,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_wpa2_psk_requires_password",
        scan::test_security_type_wpa2_psk_requires_password,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_wpa3_sae_requires_password",
        scan::test_security_type_wpa3_sae_requires_password,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_enterprise_requires_password",
        scan::test_security_type_enterprise_requires_password,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_unknown_requires_password",
        scan::test_security_type_unknown_requires_password,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_equality",
        scan::test_security_type_equality,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_copy",
        scan::test_security_type_copy,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "security_type_clone",
        scan::test_security_type_clone,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_signal_quality_excellent",
        scan::test_scan_result_signal_quality_excellent,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_signal_quality_boundary_50",
        scan::test_scan_result_signal_quality_boundary_50,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_signal_quality_good",
        scan::test_scan_result_signal_quality_good,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_signal_quality_fair",
        scan::test_scan_result_signal_quality_fair,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_signal_quality_weak",
        scan::test_scan_result_signal_quality_weak,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_signal_quality_poor",
        scan::test_scan_result_signal_quality_poor,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_signal_quality_none",
        scan::test_scan_result_signal_quality_none,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_frequency_2ghz_channel_1",
        scan::test_scan_result_frequency_2ghz_channel_1,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_frequency_2ghz_channel_6",
        scan::test_scan_result_frequency_2ghz_channel_6,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_frequency_2ghz_channel_11",
        scan::test_scan_result_frequency_2ghz_channel_11,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_frequency_5ghz_channel_36",
        scan::test_scan_result_frequency_5ghz_channel_36,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_frequency_5ghz_channel_149",
        scan::test_scan_result_frequency_5ghz_channel_149,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_band_2ghz",
        scan::test_scan_result_band_2ghz,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_band_5ghz",
        scan::test_scan_result_band_5ghz,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_band_6ghz",
        scan::test_scan_result_band_6ghz,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_default_has_channels",
        scan::test_scan_config_default_has_channels,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_default_dwell_active",
        scan::test_scan_config_default_dwell_active,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_default_dwell_passive",
        scan::test_scan_config_default_dwell_passive,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_default_not_passive",
        scan::test_scan_config_default_not_passive,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_default_no_ssid_filter",
        scan::test_scan_config_default_no_ssid_filter,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_2ghz_only_channels",
        scan::test_scan_config_2ghz_only_channels,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_5ghz_only_channels",
        scan::test_scan_config_5ghz_only_channels,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_with_ssid",
        scan::test_scan_config_with_ssid,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_with_passive",
        scan::test_scan_config_with_passive,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_builder_chain",
        scan::test_scan_config_builder_chain,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_result_clone",
        scan::test_scan_result_clone,
        "drivers/wifi/scan",
    ));
    suite.add(TestCase::with_category(
        "scan_config_clone",
        scan::test_scan_config_clone,
        "drivers/wifi/scan",
    ));

    let (_, failed, _) = suite.run_all();
    failed == 0
}
