// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors

pub mod config;
pub mod enable;
pub mod find;
pub mod types;

use crate::test::framework::{TestCase, TestSuite};

pub fn run_all() -> bool {
    let mut suite = TestSuite::new("Bus");

    suite.add(TestCase::new(
        "pci_device_empty_creation",
        types::test_pci_device_empty_creation,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_empty_is_invalid",
        types::test_pci_device_empty_is_invalid,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_with_valid_vendor_is_valid",
        types::test_pci_device_with_valid_vendor_is_valid,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_all_bars_initially_zero",
        types::test_pci_device_all_bars_initially_zero,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_irq_fields",
        types::test_pci_device_irq_fields,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_class_fields",
        types::test_pci_device_class_fields,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_header_type",
        types::test_pci_device_header_type,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_vendor_id_ffff_invalid",
        types::test_pci_device_vendor_id_ffff_invalid,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_vendor_id_zero_is_valid",
        types::test_pci_device_vendor_id_zero_is_valid,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_copy_trait",
        types::test_pci_device_copy_trait,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_clone_trait",
        types::test_pci_device_clone_trait,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_multifunction_header",
        types::test_pci_device_multifunction_header,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_standard_header",
        types::test_pci_device_standard_header,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_bridge_header",
        types::test_pci_device_bridge_header,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_cardbus_header",
        types::test_pci_device_cardbus_header,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_class_storage",
        types::test_pci_device_class_storage,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_class_network",
        types::test_pci_device_class_network,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_class_display",
        types::test_pci_device_class_display,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_class_serial_bus",
        types::test_pci_device_class_serial_bus,
        "bus/types",
    ));
    suite.add(TestCase::new("pci_device_bus_range", types::test_pci_device_bus_range, "bus/types"));
    suite.add(TestCase::new(
        "pci_device_device_range",
        types::test_pci_device_device_range,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_function_range",
        types::test_pci_device_function_range,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_intel_vendor",
        types::test_pci_device_intel_vendor,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_amd_vendor",
        types::test_pci_device_amd_vendor,
        "bus/types",
    ));
    suite.add(TestCase::new(
        "pci_device_virtio_vendor",
        types::test_pci_device_virtio_vendor,
        "bus/types",
    ));

    suite.add(TestCase::new(
        "pci_address_enable_bit",
        config::test_pci_address_enable_bit,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_bus_zero",
        config::test_pci_address_bus_zero,
        "bus/config",
    ));
    suite.add(TestCase::new("pci_address_bus_max", config::test_pci_address_bus_max, "bus/config"));
    suite.add(TestCase::new(
        "pci_address_device_zero",
        config::test_pci_address_device_zero,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_device_max",
        config::test_pci_address_device_max,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_function_zero",
        config::test_pci_address_function_zero,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_function_max",
        config::test_pci_address_function_max,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_offset_aligned",
        config::test_pci_address_offset_aligned,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_offset_alignment_mask",
        config::test_pci_address_offset_alignment_mask,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_offset_alignment_mask2",
        config::test_pci_address_offset_alignment_mask2,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_full_calculation",
        config::test_pci_address_full_calculation,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_root_complex",
        config::test_pci_address_root_complex,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_typical_device",
        config::test_pci_address_typical_device,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_vendor_id_offset",
        config::test_pci_address_vendor_id_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_device_id_offset",
        config::test_pci_address_device_id_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_command_offset",
        config::test_pci_address_command_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_status_offset",
        config::test_pci_address_status_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_class_offset",
        config::test_pci_address_class_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_header_type_offset",
        config::test_pci_address_header_type_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_bar0_offset",
        config::test_pci_address_bar0_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_bar1_offset",
        config::test_pci_address_bar1_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_bar2_offset",
        config::test_pci_address_bar2_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_bar3_offset",
        config::test_pci_address_bar3_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_bar4_offset",
        config::test_pci_address_bar4_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_bar5_offset",
        config::test_pci_address_bar5_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_interrupt_line_offset",
        config::test_pci_address_interrupt_line_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_interrupt_pin_offset",
        config::test_pci_address_interrupt_pin_offset,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_multiple_buses",
        config::test_pci_address_multiple_buses,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_multiple_devices",
        config::test_pci_address_multiple_devices,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_multiple_functions",
        config::test_pci_address_multiple_functions,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_config_address_port",
        config::test_pci_config_address_port,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_config_data_port",
        config::test_pci_config_data_port,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_bus_field_mask",
        config::test_pci_address_bus_field_mask,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_device_field_mask",
        config::test_pci_address_device_field_mask,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_function_field_mask",
        config::test_pci_address_function_field_mask,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_offset_field_mask",
        config::test_pci_address_offset_field_mask,
        "bus/config",
    ));
    suite.add(TestCase::new(
        "pci_address_all_fields_combined",
        config::test_pci_address_all_fields_combined,
        "bus/config",
    ));

    suite.add(TestCase::new(
        "get_bar_address_zero_returns_none",
        enable::test_get_bar_address_zero_returns_none,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_io_space_bit",
        enable::test_get_bar_address_io_space_bit,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_io_space_mask",
        enable::test_get_bar_address_io_space_mask,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_memory_32bit_type0",
        enable::test_get_bar_address_memory_32bit_type0,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_memory_32bit_mask",
        enable::test_get_bar_address_memory_32bit_mask,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_memory_type2_below_4g",
        enable::test_get_bar_address_memory_type2_below_4g,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_memory_type1_reserved",
        enable::test_get_bar_address_memory_type1_reserved,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_memory_type3_reserved",
        enable::test_get_bar_address_memory_type3_reserved,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_io_space_typical",
        enable::test_get_bar_address_io_space_typical,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_io_space_low_port",
        enable::test_get_bar_address_io_space_low_port,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_memory_prefetchable",
        enable::test_get_bar_address_memory_prefetchable,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_memory_non_prefetchable",
        enable::test_get_bar_address_memory_non_prefetchable,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_all_ones_io",
        enable::test_get_bar_address_all_ones_io,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_typical_mmio",
        enable::test_get_bar_address_typical_mmio,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_typical_vga",
        enable::test_get_bar_address_typical_vga,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "bar_io_bit_extraction",
        enable::test_bar_io_bit_extraction,
        "bus/enable",
    ));
    suite.add(TestCase::new("bar_type_extraction", enable::test_bar_type_extraction, "bus/enable"));
    suite.add(TestCase::new(
        "bar_prefetchable_extraction",
        enable::test_bar_prefetchable_extraction,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "command_register_bus_master_bit",
        enable::test_command_register_bus_master_bit,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "command_register_memory_space_bit",
        enable::test_command_register_memory_space_bit,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "command_register_io_space_bit",
        enable::test_command_register_io_space_bit,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_edge_case_one",
        enable::test_get_bar_address_edge_case_one,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_edge_case_two",
        enable::test_get_bar_address_edge_case_two,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_small_memory",
        enable::test_get_bar_address_small_memory,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_page_aligned",
        enable::test_get_bar_address_page_aligned,
        "bus/enable",
    ));
    suite.add(TestCase::new(
        "get_bar_address_megabyte_aligned",
        enable::test_get_bar_address_megabyte_aligned,
        "bus/enable",
    ));

    suite.add(TestCase::new(
        "device_count_returns_value",
        find::test_device_count_returns_value,
        "bus/find",
    ));
    suite.add(TestCase::new("is_init_returns_bool", find::test_is_init_returns_bool, "bus/find"));
    suite.add(TestCase::new(
        "get_device_out_of_bounds",
        find::test_get_device_out_of_bounds,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "get_device_at_max_index",
        find::test_get_device_at_max_index,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_by_id_nonexistent",
        find::test_find_device_by_id_nonexistent,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_nonexistent_class",
        find::test_find_device_nonexistent_class,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_with_prog_if_nonexistent",
        find::test_find_device_with_prog_if_nonexistent,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_devices_empty_class",
        find::test_find_devices_empty_class,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "pci_device_class_constants",
        find::test_pci_device_class_constants,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "storage_subclass_constants",
        find::test_storage_subclass_constants,
        "bus/find",
    ));
    suite.add(TestCase::new("usb_prog_if_constants", find::test_usb_prog_if_constants, "bus/find"));
    suite.add(TestCase::new(
        "bridge_subclass_constants",
        find::test_bridge_subclass_constants,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "device_count_consistent",
        find::test_device_count_consistent,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_storage_nvme",
        find::test_find_device_storage_nvme,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_storage_sata",
        find::test_find_device_storage_sata,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_network_ethernet",
        find::test_find_device_network_ethernet,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_display_vga",
        find::test_find_device_display_vga,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_serial_usb",
        find::test_find_device_serial_usb,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_bridge_host",
        find::test_find_device_bridge_host,
        "bus/find",
    ));
    suite.add(TestCase::new(
        "find_device_bridge_pci",
        find::test_find_device_bridge_pci,
        "bus/find",
    ));
    suite.add(TestCase::new("find_devices_iterator", find::test_find_devices_iterator, "bus/find"));
    suite.add(TestCase::new(
        "find_device_by_id_intel",
        find::test_find_device_by_id_intel,
        "bus/find",
    ));
    suite.add(TestCase::new("find_device_by_id_amd", find::test_find_device_by_id_amd, "bus/find"));
    suite.add(TestCase::new(
        "find_device_by_id_virtio",
        find::test_find_device_by_id_virtio,
        "bus/find",
    ));
    suite.add(TestCase::new("find_device_usb_uhci", find::test_find_device_usb_uhci, "bus/find"));
    suite.add(TestCase::new("find_device_usb_ohci", find::test_find_device_usb_ohci, "bus/find"));
    suite.add(TestCase::new("find_device_usb_ehci", find::test_find_device_usb_ehci, "bus/find"));
    suite.add(TestCase::new("find_device_usb_xhci", find::test_find_device_usb_xhci, "bus/find"));
    suite.add(TestCase::new("get_device_first", find::test_get_device_first, "bus/find"));
    suite.add(TestCase::new("get_device_boundary", find::test_get_device_boundary, "bus/find"));
    suite.add(TestCase::new(
        "get_device_past_boundary",
        find::test_get_device_past_boundary,
        "bus/find",
    ));

    let (_, failed, _) = suite.run_all();
    failed == 0
}
