// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors

pub mod handoff_api;
pub mod handoff_types;

use crate::test::framework::{TestCase, TestSuite};

pub fn run_all() -> bool {
    let mut suite = TestSuite::new("Boot");

    suite.add(TestCase::new(
        "handoff_magic_value",
        handoff_types::test_handoff_magic_value,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_version_value",
        handoff_types::test_handoff_version_value,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "max_cmdline_value",
        handoff_types::test_max_cmdline_value,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "validate_cmdline_len_valid",
        handoff_types::test_validate_cmdline_len_valid,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "validate_cmdline_len_invalid",
        handoff_types::test_validate_cmdline_len_invalid,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "truncate_cmdline_short",
        handoff_types::test_truncate_cmdline_short,
        "boot/handoff",
    ));
    suite.add(TestCase::new("flags_wx", handoff_types::test_flags_wx, "boot/handoff"));
    suite.add(TestCase::new("flags_nxe", handoff_types::test_flags_nxe, "boot/handoff"));
    suite.add(TestCase::new("flags_smep", handoff_types::test_flags_smep, "boot/handoff"));
    suite.add(TestCase::new("flags_smap", handoff_types::test_flags_smap, "boot/handoff"));
    suite.add(TestCase::new("flags_umip", handoff_types::test_flags_umip, "boot/handoff"));
    suite.add(TestCase::new(
        "flags_idmap_preserved",
        handoff_types::test_flags_idmap_preserved,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "flags_fb_available",
        handoff_types::test_flags_fb_available,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "flags_acpi_available",
        handoff_types::test_flags_acpi_available,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "flags_tpm_measured",
        handoff_types::test_flags_tpm_measured,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "flags_secure_boot",
        handoff_types::test_flags_secure_boot,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "flags_zk_attested",
        handoff_types::test_flags_zk_attested,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "flags_flag_names_empty",
        handoff_types::test_flags_flag_names_empty,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "flags_flag_names_single",
        handoff_types::test_flags_flag_names_single,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "flags_flag_names_multiple",
        handoff_types::test_flags_flag_names_multiple,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "pixel_format_rgb",
        handoff_types::test_pixel_format_rgb,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "pixel_format_bgr",
        handoff_types::test_pixel_format_bgr,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "pixel_format_rgbx",
        handoff_types::test_pixel_format_rgbx,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "pixel_format_bgrx",
        handoff_types::test_pixel_format_bgrx,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_reserved",
        handoff_types::test_memory_type_reserved,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_loader_code",
        handoff_types::test_memory_type_loader_code,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_loader_data",
        handoff_types::test_memory_type_loader_data,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_boot_services_code",
        handoff_types::test_memory_type_boot_services_code,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_boot_services_data",
        handoff_types::test_memory_type_boot_services_data,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_runtime_services_code",
        handoff_types::test_memory_type_runtime_services_code,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_runtime_services_data",
        handoff_types::test_memory_type_runtime_services_data,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_conventional",
        handoff_types::test_memory_type_conventional,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_unusable",
        handoff_types::test_memory_type_unusable,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_acpi_reclaim",
        handoff_types::test_memory_type_acpi_reclaim,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_acpi_nvs",
        handoff_types::test_memory_type_acpi_nvs,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_mmio",
        handoff_types::test_memory_type_mmio,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_mmio_port_space",
        handoff_types::test_memory_type_mmio_port_space,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_pal_code",
        handoff_types::test_memory_type_pal_code,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_type_persistent",
        handoff_types::test_memory_type_persistent,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_map_entry_size",
        handoff_types::test_memory_map_entry_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_map_size",
        handoff_types::test_memory_map_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_memory_map_default",
        handoff_types::test_memory_map_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_struct_size",
        handoff_types::test_framebuffer_info_struct_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_default",
        handoff_types::test_framebuffer_info_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_is_valid_default",
        handoff_types::test_framebuffer_info_is_valid_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_is_valid_valid",
        handoff_types::test_framebuffer_info_is_valid_valid,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_is_valid_zero_ptr",
        handoff_types::test_framebuffer_info_is_valid_zero_ptr,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_bytes_per_pixel_rgb",
        handoff_types::test_framebuffer_info_bytes_per_pixel_rgb,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_bytes_per_pixel_bgr",
        handoff_types::test_framebuffer_info_bytes_per_pixel_bgr,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_bytes_per_pixel_rgbx",
        handoff_types::test_framebuffer_info_bytes_per_pixel_rgbx,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_framebuffer_info_bytes_per_pixel_bgrx",
        handoff_types::test_framebuffer_info_bytes_per_pixel_bgrx,
        "boot/handoff",
    ));
    suite.add(TestCase::new("acpi_info_size", handoff_types::test_acpi_info_size, "boot/handoff"));
    suite.add(TestCase::new(
        "acpi_info_default",
        handoff_types::test_acpi_info_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "smbios_info_size",
        handoff_types::test_smbios_info_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "smbios_info_default",
        handoff_types::test_smbios_info_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "module_struct_size",
        handoff_types::test_module_struct_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new("module_default", handoff_types::test_module_default, "boot/handoff"));
    suite.add(TestCase::new("modules_size", handoff_types::test_modules_size, "boot/handoff"));
    suite.add(TestCase::new(
        "modules_default",
        handoff_types::test_modules_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new("timing_size", handoff_types::test_timing_size, "boot/handoff"));
    suite.add(TestCase::new("timing_default", handoff_types::test_timing_default, "boot/handoff"));
    suite.add(TestCase::new(
        "measurements_size",
        handoff_types::test_measurements_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "measurements_default",
        handoff_types::test_measurements_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "zk_attestation_size",
        handoff_types::test_zk_attestation_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "zk_attestation_default",
        handoff_types::test_zk_attestation_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new("rng_seed_size", handoff_types::test_rng_seed_size, "boot/handoff"));
    suite.add(TestCase::new(
        "rng_seed_default",
        handoff_types::test_rng_seed_default,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_default_is_valid",
        handoff_types::test_boot_handoff_v1_default_is_valid,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_default_magic",
        handoff_types::test_boot_handoff_v1_default_magic,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_default_version",
        handoff_types::test_boot_handoff_v1_default_version,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_default_size",
        handoff_types::test_boot_handoff_v1_default_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_invalid_magic",
        handoff_types::test_boot_handoff_v1_invalid_magic,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_invalid_version",
        handoff_types::test_boot_handoff_v1_invalid_version,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_invalid_size",
        handoff_types::test_boot_handoff_v1_invalid_size,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_has_flag_none",
        handoff_types::test_boot_handoff_v1_has_flag_none,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_has_flag_single",
        handoff_types::test_boot_handoff_v1_has_flag_single,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_has_flag_multiple",
        handoff_types::test_boot_handoff_v1_has_flag_multiple,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_framebuffer_none",
        handoff_types::test_boot_handoff_v1_framebuffer_none,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_framebuffer_flag_but_null_ptr",
        handoff_types::test_boot_handoff_v1_framebuffer_flag_but_null_ptr,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_framebuffer_valid",
        handoff_types::test_boot_handoff_v1_framebuffer_valid,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_acpi_rsdp_none",
        handoff_types::test_boot_handoff_v1_acpi_rsdp_none,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_acpi_rsdp_flag_but_null",
        handoff_types::test_boot_handoff_v1_acpi_rsdp_flag_but_null,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_acpi_rsdp_valid",
        handoff_types::test_boot_handoff_v1_acpi_rsdp_valid,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_secure_boot_disabled",
        handoff_types::test_boot_handoff_v1_secure_boot_disabled,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_secure_boot_via_flag",
        handoff_types::test_boot_handoff_v1_secure_boot_via_flag,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_secure_boot_via_meas",
        handoff_types::test_boot_handoff_v1_secure_boot_via_meas,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_kernel_verified_false",
        handoff_types::test_boot_handoff_v1_kernel_verified_false,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_kernel_verified_true",
        handoff_types::test_boot_handoff_v1_kernel_verified_true,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_clone",
        handoff_types::test_boot_handoff_v1_clone,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "boot_handoff_v1_copy",
        handoff_types::test_boot_handoff_v1_copy,
        "boot/handoff",
    ));

    suite.add(TestCase::new(
        "handoff_error_null_pointer_str",
        handoff_api::test_handoff_error_null_pointer_str,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_invalid_magic_str",
        handoff_api::test_handoff_error_invalid_magic_str,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_version_mismatch_str",
        handoff_api::test_handoff_error_version_mismatch_str,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_size_mismatch_str",
        handoff_api::test_handoff_error_size_mismatch_str,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_already_initialized_str",
        handoff_api::test_handoff_error_already_initialized_str,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_invalid_data_str",
        handoff_api::test_handoff_error_invalid_data_str,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_equality",
        handoff_api::test_handoff_error_equality,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_not_equal_different_variants",
        handoff_api::test_handoff_error_not_equal_different_variants,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_clone",
        handoff_api::test_handoff_error_clone,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_error_copy",
        handoff_api::test_handoff_error_copy,
        "boot/handoff",
    ));
    suite.add(TestCase::new(
        "handoff_version_current",
        handoff_api::test_handoff_version_current,
        "boot/handoff",
    ));

    let (_, failed, _) = suite.run_all();
    failed == 0
}
