use super::computed::{ComputedStyle, TextAlign};
use super::super::types::CssValue;
use super::super::properties::*;

pub fn default_style() -> ComputedStyle {
    ComputedStyle {
        display: Display::default(),
        position: Position::default(),
        box_sizing: BoxSizing::default(),
        width: CssValue::Auto,
        height: CssValue::Auto,
        min_width: CssValue::Auto,
        max_width: CssValue::None,
        min_height: CssValue::Auto,
        max_height: CssValue::None,
        margin_top: CssValue::Length(0.0, super::super::types::Unit::Px),
        margin_right: CssValue::Length(0.0, super::super::types::Unit::Px),
        margin_bottom: CssValue::Length(0.0, super::super::types::Unit::Px),
        margin_left: CssValue::Length(0.0, super::super::types::Unit::Px),
        padding_top: CssValue::Length(0.0, super::super::types::Unit::Px),
        padding_right: CssValue::Length(0.0, super::super::types::Unit::Px),
        padding_bottom: CssValue::Length(0.0, super::super::types::Unit::Px),
        padding_left: CssValue::Length(0.0, super::super::types::Unit::Px),
        border_top_width: CssValue::Length(0.0, super::super::types::Unit::Px),
        border_right_width: CssValue::Length(0.0, super::super::types::Unit::Px),
        border_bottom_width: CssValue::Length(0.0, super::super::types::Unit::Px),
        border_left_width: CssValue::Length(0.0, super::super::types::Unit::Px),
        border_top_style: BorderStyle::default(),
        border_top_color: None,
        color: None,
        background_color: None,
        font_size: CssValue::Length(16.0, super::super::types::Unit::Px),
        font_weight: FontWeight::default(),
        font_style: FontStyle::default(),
        text_decoration: TextDecoration::default(),
        text_align: TextAlign::default(),
        line_height: CssValue::Number(1.2),
        white_space: WhiteSpace::default(),
        visibility: Visibility::default(),
        opacity: 1.0,
        overflow: Overflow::default(),
        float: Float::default(),
        clear: Clear::default(),
        top: CssValue::Auto,
        right: CssValue::Auto,
        bottom: CssValue::Auto,
        left: CssValue::Auto,
        z_index: CssValue::Auto,
        flex_direction: FlexDirection::default(),
        flex_wrap: FlexWrap::default(),
        justify_content: JustifyContent::default(),
        align_items: AlignItems::default(),
        flex_grow: 0.0,
        flex_shrink: 1.0,
        flex_basis: CssValue::Auto,
        order: 0,
    }
}
