// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// Crypto subsystem test suite - 231 tests across 8 modules

pub mod asymmetric;
pub mod constant_time;
pub mod error;
pub mod hashing;
pub mod pqc;
pub mod rng;
pub mod symmetric;
pub mod zk;

use crate::test::framework::{TestCase, TestSuite};

/// Run all crypto subsystem tests.
/// Returns true if all tests pass.
pub fn run_all() -> bool {
    let mut suite = TestSuite::new("Crypto");

    // Symmetric encryption tests (AES-GCM, ChaCha20-Poly1305) - 37 tests
    suite.add(TestCase::new(
        "aes128_gcm_nist_case_1",
        symmetric::test_aes128_gcm_nist_case_1,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_nist_case_2",
        symmetric::test_aes128_gcm_nist_case_2,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_roundtrip",
        symmetric::test_aes128_gcm_roundtrip,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_tag_tampering",
        symmetric::test_aes128_gcm_tag_tampering,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_ciphertext_tampering",
        symmetric::test_aes128_gcm_ciphertext_tampering,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_aad_tampering",
        symmetric::test_aes128_gcm_aad_tampering,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_short_ciphertext",
        symmetric::test_aes128_gcm_short_ciphertext,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_empty_plaintext",
        symmetric::test_aes128_gcm_empty_plaintext,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_empty_aad",
        symmetric::test_aes128_gcm_empty_aad,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_in_place",
        symmetric::test_aes128_gcm_in_place,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_in_place_tag_tamper",
        symmetric::test_aes128_gcm_in_place_tag_tamper,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes128_gcm_large_plaintext",
        symmetric::test_aes128_gcm_large_plaintext,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes256_gcm_roundtrip",
        symmetric::test_aes256_gcm_roundtrip,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes256_gcm_tag_tampering",
        symmetric::test_aes256_gcm_tag_tampering,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes256_gcm_ciphertext_tampering",
        symmetric::test_aes256_gcm_ciphertext_tampering,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes256_gcm_empty_plaintext",
        symmetric::test_aes256_gcm_empty_plaintext,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes256_gcm_in_place",
        symmetric::test_aes256_gcm_in_place,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_rfc8439_block",
        symmetric::test_chacha20_rfc8439_block,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_rfc8439_aead",
        symmetric::test_chacha20_poly1305_rfc8439_aead,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_tag_tampering",
        symmetric::test_chacha20_poly1305_tag_tampering,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_ciphertext_tampering",
        symmetric::test_chacha20_poly1305_ciphertext_tampering,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_aad_tampering",
        symmetric::test_chacha20_poly1305_aad_tampering,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_empty_plaintext",
        symmetric::test_chacha20_poly1305_empty_plaintext,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_empty_aad",
        symmetric::test_chacha20_poly1305_empty_aad,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_in_place",
        symmetric::test_chacha20_poly1305_in_place,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_large_plaintext",
        symmetric::test_chacha20_poly1305_large_plaintext,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "poly1305_rfc8439_mac",
        symmetric::test_poly1305_rfc8439_mac,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "poly1305_deterministic",
        symmetric::test_poly1305_deterministic,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_short_ciphertext",
        symmetric::test_chacha20_poly1305_short_ciphertext,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_different_keys",
        symmetric::test_chacha20_poly1305_different_keys,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_different_nonces",
        symmetric::test_chacha20_poly1305_different_nonces,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes_gcm_different_keys",
        symmetric::test_aes_gcm_different_keys,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes_gcm_different_nonces",
        symmetric::test_aes_gcm_different_nonces,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes_gcm_cross_key_decrypt",
        symmetric::test_aes_gcm_cross_key_decrypt,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_cross_key_decrypt",
        symmetric::test_chacha20_poly1305_cross_key_decrypt,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "aes_gcm_wrong_nonce",
        symmetric::test_aes_gcm_wrong_nonce,
        "crypto/symmetric",
    ));
    suite.add(TestCase::new(
        "chacha20_poly1305_wrong_nonce",
        symmetric::test_chacha20_poly1305_wrong_nonce,
        "crypto/symmetric",
    ));

    // Asymmetric cryptography tests (Ed25519) - 23 tests
    suite.add(TestCase::new(
        "ed25519_keypair_from_seed",
        asymmetric::test_ed25519_keypair_from_seed,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_keypair_deterministic",
        asymmetric::test_ed25519_keypair_deterministic,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_keypair_different_seeds",
        asymmetric::test_ed25519_keypair_different_seeds,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_sign_verify_roundtrip",
        asymmetric::test_ed25519_sign_verify_roundtrip,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_sign_deterministic",
        asymmetric::test_ed25519_sign_deterministic,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_verify_wrong_message",
        asymmetric::test_ed25519_verify_wrong_message,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_verify_wrong_key",
        asymmetric::test_ed25519_verify_wrong_key,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_verify_tampered_signature_r",
        asymmetric::test_ed25519_verify_tampered_signature_r,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_verify_tampered_signature_s",
        asymmetric::test_ed25519_verify_tampered_signature_s,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_signature_to_bytes",
        asymmetric::test_ed25519_signature_to_bytes,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_signature_from_bytes",
        asymmetric::test_ed25519_signature_from_bytes,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_signature_roundtrip_bytes",
        asymmetric::test_ed25519_signature_roundtrip_bytes,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_sign_empty_message",
        asymmetric::test_ed25519_sign_empty_message,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_sign_large_message",
        asymmetric::test_ed25519_sign_large_message,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_keypair_clone",
        asymmetric::test_ed25519_keypair_clone,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_signature_clone",
        asymmetric::test_ed25519_signature_clone,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_public_key_size",
        asymmetric::test_ed25519_public_key_size,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_private_key_size",
        asymmetric::test_ed25519_private_key_size,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_signature_size",
        asymmetric::test_ed25519_signature_size,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_sign_different_messages_different_sigs",
        asymmetric::test_ed25519_sign_different_messages_different_sigs,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_all_zero_seed",
        asymmetric::test_ed25519_all_zero_seed,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_all_ones_seed",
        asymmetric::test_ed25519_all_ones_seed,
        "crypto/asymmetric",
    ));
    suite.add(TestCase::new(
        "ed25519_sequential_signing",
        asymmetric::test_ed25519_sequential_signing,
        "crypto/asymmetric",
    ));

    // Hashing tests (BLAKE3, SHA-3, SHA-256/512, HMAC, HKDF, RIPEMD-160, Keccak256) - 51 tests
    suite.add(TestCase::new("blake3_empty", hashing::test_blake3_empty, "crypto/hashing"));
    suite.add(TestCase::new("blake3_abc", hashing::test_blake3_abc, "crypto/hashing"));
    suite.add(TestCase::new(
        "blake3_deterministic",
        hashing::test_blake3_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "blake3_different_inputs",
        hashing::test_blake3_different_inputs,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("blake3_keyed", hashing::test_blake3_keyed, "crypto/hashing"));
    suite.add(TestCase::new(
        "blake3_keyed_deterministic",
        hashing::test_blake3_keyed_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "blake3_keyed_different_keys",
        hashing::test_blake3_keyed_different_keys,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "blake3_derive_key",
        hashing::test_blake3_derive_key,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "blake3_derive_key_deterministic",
        hashing::test_blake3_derive_key_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("blake3_xof", hashing::test_blake3_xof, "crypto/hashing"));
    suite.add(TestCase::new(
        "blake3_xof_128_bytes",
        hashing::test_blake3_xof_128_bytes,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("sha3_256_empty", hashing::test_sha3_256_empty, "crypto/hashing"));
    suite.add(TestCase::new("sha3_256_abc", hashing::test_sha3_256_abc, "crypto/hashing"));
    suite.add(TestCase::new(
        "sha3_256_deterministic",
        hashing::test_sha3_256_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("sha3_512_empty", hashing::test_sha3_512_empty, "crypto/hashing"));
    suite.add(TestCase::new("sha3_512_abc", hashing::test_sha3_512_abc, "crypto/hashing"));
    suite.add(TestCase::new(
        "sha3_512_deterministic",
        hashing::test_sha3_512_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "sha3_256_vs_512_different",
        hashing::test_sha3_256_vs_512_different,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("shake128_basic", hashing::test_shake128_basic, "crypto/hashing"));
    suite.add(TestCase::new(
        "shake128_variable_output",
        hashing::test_shake128_variable_output,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("shake256_basic", hashing::test_shake256_basic, "crypto/hashing"));
    suite.add(TestCase::new(
        "shake256_variable_output",
        hashing::test_shake256_variable_output,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("keccak256_empty", hashing::test_keccak256_empty, "crypto/hashing"));
    suite.add(TestCase::new(
        "keccak256_deterministic",
        hashing::test_keccak256_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "keccak256_vs_sha3_256_different",
        hashing::test_keccak256_vs_sha3_256_different,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("sha512_empty", hashing::test_sha512_empty, "crypto/hashing"));
    suite.add(TestCase::new("sha512_abc", hashing::test_sha512_abc, "crypto/hashing"));
    suite.add(TestCase::new(
        "sha512_deterministic",
        hashing::test_sha512_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "sha512_hash_struct",
        hashing::test_sha512_hash_struct,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("sha256_empty", hashing::test_sha256_empty, "crypto/hashing"));
    suite.add(TestCase::new("sha256_abc", hashing::test_sha256_abc, "crypto/hashing"));
    suite.add(TestCase::new(
        "sha256_deterministic",
        hashing::test_sha256_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hmac_sha256_basic",
        hashing::test_hmac_sha256_basic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hmac_sha256_deterministic",
        hashing::test_hmac_sha256_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hmac_sha256_different_keys",
        hashing::test_hmac_sha256_different_keys,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hmac_sha256_different_messages",
        hashing::test_hmac_sha256_different_messages,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hmac_verify_valid",
        hashing::test_hmac_verify_valid,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hmac_verify_invalid_mac",
        hashing::test_hmac_verify_invalid_mac,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hmac_verify_wrong_key",
        hashing::test_hmac_verify_wrong_key,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hmac_verify_wrong_message",
        hashing::test_hmac_verify_wrong_message,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hkdf_expand_basic",
        hashing::test_hkdf_expand_basic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hkdf_expand_deterministic",
        hashing::test_hkdf_expand_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hkdf_expand_different_info",
        hashing::test_hkdf_expand_different_info,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "hkdf_expand_64_bytes",
        hashing::test_hkdf_expand_64_bytes,
        "crypto/hashing",
    ));
    suite.add(TestCase::new("ripemd160_empty", hashing::test_ripemd160_empty, "crypto/hashing"));
    suite.add(TestCase::new("ripemd160_abc", hashing::test_ripemd160_abc, "crypto/hashing"));
    suite.add(TestCase::new(
        "ripemd160_deterministic",
        hashing::test_ripemd160_deterministic,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "different_hash_algorithms_different_output",
        hashing::test_different_hash_algorithms_different_output,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "large_input_hashing",
        hashing::test_large_input_hashing,
        "crypto/hashing",
    ));
    suite.add(TestCase::new(
        "single_byte_inputs_all_different",
        hashing::test_single_byte_inputs_all_different,
        "crypto/hashing",
    ));

    // Post-quantum cryptography tests (SPHINCS+, Kyber, MlDsa65) - 29 tests
    suite.add(TestCase::new(
        "sphincs_security_parameter",
        pqc::test_sphincs_security_parameter,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_fors_parameters",
        pqc::test_sphincs_fors_parameters,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_wots_parameter",
        pqc::test_sphincs_wots_parameter,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_tree_parameters",
        pqc::test_sphincs_tree_parameters,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_public_key_size",
        pqc::test_sphincs_public_key_size,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_secret_key_size",
        pqc::test_sphincs_secret_key_size,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_signature_size",
        pqc::test_sphincs_signature_size,
        "crypto/pqc",
    ));
    suite.add(TestCase::new("sphincs_wots_len", pqc::test_sphincs_wots_len, "crypto/pqc"));
    suite.add(TestCase::new(
        "sphincs_wots_sig_size",
        pqc::test_sphincs_wots_sig_size,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_fors_sig_size",
        pqc::test_sphincs_fors_sig_size,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_pk_seed_bytes",
        pqc::test_sphincs_pk_seed_bytes,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_pk_root_bytes",
        pqc::test_sphincs_pk_root_bytes,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_sk_seed_bytes",
        pqc::test_sphincs_sk_seed_bytes,
        "crypto/pqc",
    ));
    suite.add(TestCase::new("sphincs_sk_prf_bytes", pqc::test_sphincs_sk_prf_bytes, "crypto/pqc"));
    suite.add(TestCase::new("sphincs_param_name", pqc::test_sphincs_param_name, "crypto/pqc"));
    suite.add(TestCase::new(
        "sphincs_constants_consistency",
        pqc::test_sphincs_constants_consistency,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_signature_larger_than_classical",
        pqc::test_sphincs_signature_larger_than_classical,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_pk_larger_than_classical",
        pqc::test_sphincs_pk_larger_than_classical,
        "crypto/pqc",
    ));
    suite.add(TestCase::new("kyber_sizes", pqc::test_kyber_sizes, "crypto/pqc"));
    suite.add(TestCase::new(
        "kyber_ciphertext_sizes",
        pqc::test_kyber_ciphertext_sizes,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "kyber_shared_secret_size",
        pqc::test_kyber_shared_secret_size,
        "crypto/pqc",
    ));
    suite.add(TestCase::new("ml_dsa_65_sizes", pqc::test_ml_dsa_65_sizes, "crypto/pqc"));
    suite.add(TestCase::new(
        "ml_dsa_65_signature_sizes",
        pqc::test_ml_dsa_65_signature_sizes,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "ml_dsa_65_secret_key_sizes",
        pqc::test_ml_dsa_65_secret_key_sizes,
        "crypto/pqc",
    ));
    suite.add(TestCase::new("pqc_security_levels", pqc::test_pqc_security_levels, "crypto/pqc"));
    suite.add(TestCase::new(
        "sphincs_wots_len1_calculation",
        pqc::test_sphincs_wots_len1_calculation,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "sphincs_tree_height_per_layer",
        pqc::test_sphincs_tree_height_per_layer,
        "crypto/pqc",
    ));
    suite.add(TestCase::new(
        "pqc_vs_classical_sizes",
        pqc::test_pqc_vs_classical_sizes,
        "crypto/pqc",
    ));

    // Zero-knowledge proof tests (attestations, commitments, credentials) - 27 tests
    suite.add(TestCase::new(
        "attestation_create_verify",
        zk::test_attestation_create_verify,
        "crypto/zk",
    ));
    suite.add(TestCase::new(
        "attestation_wrong_data",
        zk::test_attestation_wrong_data,
        "crypto/zk",
    ));
    suite.add(TestCase::new("attestation_wrong_key", zk::test_attestation_wrong_key, "crypto/zk"));
    suite.add(TestCase::new(
        "attestation_deterministic",
        zk::test_attestation_deterministic,
        "crypto/zk",
    ));
    suite.add(TestCase::new("commit_verify", zk::test_commit_verify, "crypto/zk"));
    suite.add(TestCase::new("commit_wrong_value", zk::test_commit_wrong_value, "crypto/zk"));
    suite.add(TestCase::new(
        "commit_wrong_randomness",
        zk::test_commit_wrong_randomness,
        "crypto/zk",
    ));
    suite.add(TestCase::new("commit_deterministic", zk::test_commit_deterministic, "crypto/zk"));
    suite.add(TestCase::new(
        "commit_different_values_different_commitments",
        zk::test_commit_different_values_different_commitments,
        "crypto/zk",
    ));
    suite.add(TestCase::new(
        "commit_different_randomness_different_commitments",
        zk::test_commit_different_randomness_different_commitments,
        "crypto/zk",
    ));
    suite.add(TestCase::new("commit_u64", zk::test_commit_u64, "crypto/zk"));
    suite.add(TestCase::new(
        "commit_u64_deterministic",
        zk::test_commit_u64_deterministic,
        "crypto/zk",
    ));
    suite.add(TestCase::new(
        "commit_u64_different_values",
        zk::test_commit_u64_different_values,
        "crypto/zk",
    ));
    suite.add(TestCase::new(
        "credential_issue_verify",
        zk::test_credential_issue_verify,
        "crypto/zk",
    ));
    suite.add(TestCase::new(
        "credential_tampered_signature",
        zk::test_credential_tampered_signature,
        "crypto/zk",
    ));
    suite.add(TestCase::new(
        "credential_different_issuers",
        zk::test_credential_different_issuers,
        "crypto/zk",
    ));
    suite.add(TestCase::new("zeroize_mut", zk::test_zeroize_mut, "crypto/zk"));
    suite.add(TestCase::new("zeroize_array", zk::test_zeroize_array, "crypto/zk"));
    suite.add(TestCase::new("zeroize_empty", zk::test_zeroize_empty, "crypto/zk"));
    suite.add(TestCase::new(
        "attestation_empty_data",
        zk::test_attestation_empty_data,
        "crypto/zk",
    ));
    suite.add(TestCase::new(
        "attestation_large_data",
        zk::test_attestation_large_data,
        "crypto/zk",
    ));
    suite.add(TestCase::new("commit_empty_value", zk::test_commit_empty_value, "crypto/zk"));
    suite.add(TestCase::new("commit_large_value", zk::test_commit_large_value, "crypto/zk"));
    suite.add(TestCase::new("groth16_proof_size", zk::test_groth16_proof_size, "crypto/zk"));
    suite.add(TestCase::new("plonk_proof_size", zk::test_plonk_proof_size, "crypto/zk"));
    suite.add(TestCase::new("field_element_size", zk::test_field_element_size, "crypto/zk"));

    // Random number generator tests (ChaCha-based CSPRNG) - 27 tests
    suite.add(TestCase::new("chacha_rng_new", rng::test_chacha_rng_new, "crypto/rng"));
    suite.add(TestCase::new(
        "chacha_rng_fill_bytes",
        rng::test_chacha_rng_fill_bytes,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_deterministic",
        rng::test_chacha_rng_deterministic,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_different_seeds",
        rng::test_chacha_rng_different_seeds,
        "crypto/rng",
    ));
    suite.add(TestCase::new("chacha_rng_next_u64", rng::test_chacha_rng_next_u64, "crypto/rng"));
    suite.add(TestCase::new(
        "chacha_rng_next_u64_deterministic",
        rng::test_chacha_rng_next_u64_deterministic,
        "crypto/rng",
    ));
    suite.add(TestCase::new("chacha_rng_next_u32", rng::test_chacha_rng_next_u32, "crypto/rng"));
    suite.add(TestCase::new(
        "chacha_rng_next_u32_deterministic",
        rng::test_chacha_rng_next_u32_deterministic,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_multiple_calls",
        rng::test_chacha_rng_multiple_calls,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_blocks_generated",
        rng::test_chacha_rng_blocks_generated,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_needs_reseed_initial",
        rng::test_chacha_rng_needs_reseed_initial,
        "crypto/rng",
    ));
    suite.add(TestCase::new("chacha_rng_reseed", rng::test_chacha_rng_reseed, "crypto/rng"));
    suite.add(TestCase::new(
        "chacha_rng_reseed_changes_output",
        rng::test_chacha_rng_reseed_changes_output,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_reseed_deterministic",
        rng::test_chacha_rng_reseed_deterministic,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_fill_small",
        rng::test_chacha_rng_fill_small,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_fill_large",
        rng::test_chacha_rng_fill_large,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_fill_exact_block",
        rng::test_chacha_rng_fill_exact_block,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_fill_two_blocks",
        rng::test_chacha_rng_fill_two_blocks,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_fill_partial_block",
        rng::test_chacha_rng_fill_partial_block,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_fill_empty",
        rng::test_chacha_rng_fill_empty,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "reseed_interval_constant",
        rng::test_reseed_interval_constant,
        "crypto/rng",
    ));
    suite.add(TestCase::new("chacha_rng_zero_seed", rng::test_chacha_rng_zero_seed, "crypto/rng"));
    suite.add(TestCase::new(
        "chacha_rng_all_ones_seed",
        rng::test_chacha_rng_all_ones_seed,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_sequential_consistent",
        rng::test_chacha_rng_sequential_consistent,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_different_sizes_match",
        rng::test_chacha_rng_different_sizes_match,
        "crypto/rng",
    ));
    suite.add(TestCase::new(
        "chacha_rng_u32_u64_consistency",
        rng::test_chacha_rng_u32_u64_consistency,
        "crypto/rng",
    ));

    // Error handling tests (CryptoError, CryptoResult) - 25 tests
    suite.add(TestCase::new(
        "crypto_error_aead_tag_mismatch",
        error::test_crypto_error_aead_tag_mismatch,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_invalid_length",
        error::test_crypto_error_invalid_length,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_kem_error",
        error::test_crypto_error_kem_error,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_sig_error",
        error::test_crypto_error_sig_error,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_invalid_input",
        error::test_crypto_error_invalid_input,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_invalid_key",
        error::test_crypto_error_invalid_key,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_key_not_found",
        error::test_crypto_error_key_not_found,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_buffer_too_small",
        error::test_crypto_error_buffer_too_small,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_verification_failed",
        error::test_crypto_error_verification_failed,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_invalid_state",
        error::test_crypto_error_invalid_state,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_authentication_failed",
        error::test_crypto_error_authentication_failed,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_insufficient_entropy",
        error::test_crypto_error_insufficient_entropy,
        "crypto/error",
    ));
    suite.add(TestCase::new("crypto_error_clone", error::test_crypto_error_clone, "crypto/error"));
    suite.add(TestCase::new("crypto_error_copy", error::test_crypto_error_copy, "crypto/error"));
    suite.add(TestCase::new("crypto_error_debug", error::test_crypto_error_debug, "crypto/error"));
    suite.add(TestCase::new(
        "crypto_error_all_variants_distinct",
        error::test_crypto_error_all_variants_distinct,
        "crypto/error",
    ));
    suite.add(TestCase::new("crypto_result_ok", error::test_crypto_result_ok, "crypto/error"));
    suite.add(TestCase::new("crypto_result_err", error::test_crypto_result_err, "crypto/error"));
    suite.add(TestCase::new("crypto_result_map", error::test_crypto_result_map, "crypto/error"));
    suite.add(TestCase::new(
        "crypto_result_map_err",
        error::test_crypto_result_map_err,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_result_and_then",
        error::test_crypto_result_and_then,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_result_or_else",
        error::test_crypto_result_or_else,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_result_unwrap_or",
        error::test_crypto_result_unwrap_or,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_result_unwrap_or_else",
        error::test_crypto_result_unwrap_or_else,
        "crypto/error",
    ));
    suite.add(TestCase::new(
        "crypto_error_not_equal_to_different",
        error::test_crypto_error_not_equal_to_different,
        "crypto/error",
    ));

    // Constant-time operation tests - 12 tests
    suite.add(TestCase::new(
        "ct_eq_equal",
        constant_time::test_ct_eq_equal,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "ct_eq_not_equal",
        constant_time::test_ct_eq_not_equal,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "ct_eq_different_lengths",
        constant_time::test_ct_eq_different_lengths,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "ct_eq_empty",
        constant_time::test_ct_eq_empty,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "ct_select_u64_false",
        constant_time::test_ct_select_u64_false,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "ct_select_u64_true",
        constant_time::test_ct_select_u64_true,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "ct_is_zero_u64_zero",
        constant_time::test_ct_is_zero_u64_zero,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "ct_is_zero_u64_one",
        constant_time::test_ct_is_zero_u64_one,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "ct_is_zero_u64_max",
        constant_time::test_ct_is_zero_u64_max,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "secure_zero",
        constant_time::test_secure_zero,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "secure_zero_large",
        constant_time::test_secure_zero_large,
        "crypto/constant_time",
    ));
    suite.add(TestCase::new(
        "secure_zero_empty",
        constant_time::test_secure_zero_empty,
        "crypto/constant_time",
    ));

    let (_, failed, _) = suite.run_all();
    failed == 0
}
